// <auto-generated />
using System;
using BtkApiProject.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BtkApiProject.Persistence.Migrations
{
    [DbContext(typeof(CustomDbContext))]
    [Migration("20240504135046_mig1")]
    partial class mig1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BtkApiProject.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = new Guid("dd868916-dcde-465f-a89c-313a24d230c6"),
                            CreatedDate = new DateTime(2023, 5, 8, 16, 11, 32, 318, DateTimeKind.Local).AddTicks(5157),
                            Description = "Non minima repellat nesciunt.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Book"
                        },
                        new
                        {
                            ID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2023, 10, 8, 7, 49, 5, 914, DateTimeKind.Local).AddTicks(3431),
                            Description = "Amet in maiores et vel voluptatem sit rerum.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Electronics"
                        },
                        new
                        {
                            ID = new Guid("18130346-e1b7-41d9-ba97-8e414d50457e"),
                            CreatedDate = new DateTime(2024, 3, 19, 9, 55, 51, 695, DateTimeKind.Local).AddTicks(2706),
                            Description = "Perspiciatis ut officia aut ipsam sit reiciendis.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Movie"
                        },
                        new
                        {
                            ID = new Guid("95b499c4-34a7-48a2-ac44-bc096de3fc66"),
                            CreatedDate = new DateTime(2024, 3, 31, 0, 39, 50, 124, DateTimeKind.Local).AddTicks(5227),
                            Description = "Dolorem corrupti sed.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Sport"
                        },
                        new
                        {
                            ID = new Guid("18e74e76-934f-4c06-b3ce-643c87c6dcfd"),
                            CreatedDate = new DateTime(2024, 4, 17, 23, 38, 52, 936, DateTimeKind.Local).AddTicks(708),
                            Description = "Tempora amet eligendi doloremque velit voluptatem.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Clothing"
                        },
                        new
                        {
                            ID = new Guid("b9066e07-91f7-44bb-a30b-7122aa190ecc"),
                            CreatedDate = new DateTime(2023, 7, 12, 22, 6, 11, 490, DateTimeKind.Local).AddTicks(5970),
                            Description = "Eos maiores reprehenderit veritatis consectetur quae minus quibusdam.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Accessory"
                        },
                        new
                        {
                            ID = new Guid("eba86dbf-a17a-45e5-bcbf-6aa599af3be1"),
                            CreatedDate = new DateTime(2023, 6, 10, 9, 25, 24, 645, DateTimeKind.Local).AddTicks(2030),
                            Description = "Nostrum est quod quae.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Furniture"
                        },
                        new
                        {
                            ID = new Guid("80c7de02-40f8-4c82-bd90-212560c06949"),
                            CreatedDate = new DateTime(2023, 7, 22, 23, 27, 19, 854, DateTimeKind.Local).AddTicks(932),
                            Description = "Provident dolore et.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Game"
                        },
                        new
                        {
                            ID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2023, 6, 12, 0, 18, 10, 768, DateTimeKind.Local).AddTicks(5827),
                            Description = "Mollitia itaque in et accusantium maxime hic ullam dolorem.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Art"
                        },
                        new
                        {
                            ID = new Guid("34b395e8-4e60-4e13-9ea9-043c0f10852d"),
                            CreatedDate = new DateTime(2023, 6, 23, 9, 6, 55, 309, DateTimeKind.Local).AddTicks(4546),
                            Description = "Quo quod quia eum.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Music"
                        });
                });

            modelBuilder.Entity("BtkApiProject.Domain.Entities.Joins.OrderProduct", b =>
                {
                    b.Property<Guid>("OrderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OrderID", "ProductID");

                    b.HasIndex("ProductID");

                    b.ToTable("OrderProduct");

                    b.HasData(
                        new
                        {
                            OrderID = new Guid("dd868916-dcde-465f-a89c-313a24d230c6"),
                            ProductID = new Guid("dd868916-dcde-465f-a89c-313a24d230c6")
                        },
                        new
                        {
                            OrderID = new Guid("dd868916-dcde-465f-a89c-313a24d230c6"),
                            ProductID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b")
                        },
                        new
                        {
                            OrderID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            ProductID = new Guid("18130346-e1b7-41d9-ba97-8e414d50457e")
                        },
                        new
                        {
                            OrderID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            ProductID = new Guid("95b499c4-34a7-48a2-ac44-bc096de3fc66")
                        },
                        new
                        {
                            OrderID = new Guid("18130346-e1b7-41d9-ba97-8e414d50457e"),
                            ProductID = new Guid("18e74e76-934f-4c06-b3ce-643c87c6dcfd")
                        },
                        new
                        {
                            OrderID = new Guid("18130346-e1b7-41d9-ba97-8e414d50457e"),
                            ProductID = new Guid("b9066e07-91f7-44bb-a30b-7122aa190ecc")
                        },
                        new
                        {
                            OrderID = new Guid("95b499c4-34a7-48a2-ac44-bc096de3fc66"),
                            ProductID = new Guid("eba86dbf-a17a-45e5-bcbf-6aa599af3be1")
                        },
                        new
                        {
                            OrderID = new Guid("95b499c4-34a7-48a2-ac44-bc096de3fc66"),
                            ProductID = new Guid("80c7de02-40f8-4c82-bd90-212560c06949")
                        },
                        new
                        {
                            OrderID = new Guid("18e74e76-934f-4c06-b3ce-643c87c6dcfd"),
                            ProductID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b")
                        },
                        new
                        {
                            OrderID = new Guid("18e74e76-934f-4c06-b3ce-643c87c6dcfd"),
                            ProductID = new Guid("34b395e8-4e60-4e13-9ea9-043c0f10852d")
                        },
                        new
                        {
                            OrderID = new Guid("b9066e07-91f7-44bb-a30b-7122aa190ecc"),
                            ProductID = new Guid("4804fa42-5494-4cb0-8c17-f23731b0135d")
                        },
                        new
                        {
                            OrderID = new Guid("b9066e07-91f7-44bb-a30b-7122aa190ecc"),
                            ProductID = new Guid("ef773918-5fff-4c25-84cd-f58b43442e21")
                        },
                        new
                        {
                            OrderID = new Guid("eba86dbf-a17a-45e5-bcbf-6aa599af3be1"),
                            ProductID = new Guid("a5d13a52-2dc3-4167-8b8c-4c446844898b")
                        },
                        new
                        {
                            OrderID = new Guid("eba86dbf-a17a-45e5-bcbf-6aa599af3be1"),
                            ProductID = new Guid("9072edf5-43e9-45d6-a04e-60e552ac8b57")
                        },
                        new
                        {
                            OrderID = new Guid("80c7de02-40f8-4c82-bd90-212560c06949"),
                            ProductID = new Guid("09118505-491b-46cd-b154-2f523567c531")
                        },
                        new
                        {
                            OrderID = new Guid("80c7de02-40f8-4c82-bd90-212560c06949"),
                            ProductID = new Guid("5e5589fe-77d8-49d2-9bbb-d1a42cba0bf1")
                        },
                        new
                        {
                            OrderID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            ProductID = new Guid("fefc43b4-97a8-4713-8071-51930f12cb76")
                        },
                        new
                        {
                            OrderID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            ProductID = new Guid("9a5c8eee-dfa0-4aee-8e39-c7f34bf24367")
                        },
                        new
                        {
                            OrderID = new Guid("34b395e8-4e60-4e13-9ea9-043c0f10852d"),
                            ProductID = new Guid("61d00226-a54f-43e4-b94f-ebd81c7acfb0")
                        },
                        new
                        {
                            OrderID = new Guid("34b395e8-4e60-4e13-9ea9-043c0f10852d"),
                            ProductID = new Guid("3e20bea6-3150-4551-8698-c93bcc384a09")
                        },
                        new
                        {
                            OrderID = new Guid("4804fa42-5494-4cb0-8c17-f23731b0135d"),
                            ProductID = new Guid("32a39a39-0d03-4569-8908-8f0fbd483c65")
                        },
                        new
                        {
                            OrderID = new Guid("4804fa42-5494-4cb0-8c17-f23731b0135d"),
                            ProductID = new Guid("54b58cfa-5b5e-4b2a-88cd-67e340ac758d")
                        },
                        new
                        {
                            OrderID = new Guid("ef773918-5fff-4c25-84cd-f58b43442e21"),
                            ProductID = new Guid("eac29877-cf98-49b2-b092-dabde42b829e")
                        },
                        new
                        {
                            OrderID = new Guid("ef773918-5fff-4c25-84cd-f58b43442e21"),
                            ProductID = new Guid("0d210c85-5f4c-43a6-bcc2-a9546e99601b")
                        },
                        new
                        {
                            OrderID = new Guid("a5d13a52-2dc3-4167-8b8c-4c446844898b"),
                            ProductID = new Guid("2993cc3b-48d8-4c3a-8662-9ae328688c9c")
                        },
                        new
                        {
                            OrderID = new Guid("a5d13a52-2dc3-4167-8b8c-4c446844898b"),
                            ProductID = new Guid("8df428ba-1d69-45b8-8d40-40e235c957aa")
                        },
                        new
                        {
                            OrderID = new Guid("9072edf5-43e9-45d6-a04e-60e552ac8b57"),
                            ProductID = new Guid("3500e840-e254-4823-90fc-7a8789df67f6")
                        },
                        new
                        {
                            OrderID = new Guid("9072edf5-43e9-45d6-a04e-60e552ac8b57"),
                            ProductID = new Guid("866ea2a9-8721-4251-8022-ad988bd22b8c")
                        },
                        new
                        {
                            OrderID = new Guid("09118505-491b-46cd-b154-2f523567c531"),
                            ProductID = new Guid("d11c7b91-2e92-4109-9d55-29adc4506f4f")
                        },
                        new
                        {
                            OrderID = new Guid("09118505-491b-46cd-b154-2f523567c531"),
                            ProductID = new Guid("dfbcdf14-bd61-4f63-847a-969b0c517f12")
                        });
                });

            modelBuilder.Entity("BtkApiProject.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            ID = new Guid("dd868916-dcde-465f-a89c-313a24d230c6"),
                            CreatedDate = new DateTime(2023, 5, 13, 22, 41, 28, 805, DateTimeKind.Local).AddTicks(166),
                            IsApproved = false,
                            IsDeleted = false
                        },
                        new
                        {
                            ID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2023, 11, 17, 18, 13, 58, 487, DateTimeKind.Local).AddTicks(8210),
                            IsApproved = false,
                            IsDeleted = false
                        },
                        new
                        {
                            ID = new Guid("18130346-e1b7-41d9-ba97-8e414d50457e"),
                            CreatedDate = new DateTime(2024, 5, 4, 10, 41, 28, 421, DateTimeKind.Local).AddTicks(5904),
                            IsApproved = false,
                            IsDeleted = false
                        },
                        new
                        {
                            ID = new Guid("95b499c4-34a7-48a2-ac44-bc096de3fc66"),
                            CreatedDate = new DateTime(2023, 9, 16, 15, 55, 31, 201, DateTimeKind.Local).AddTicks(8209),
                            IsApproved = false,
                            IsDeleted = false
                        },
                        new
                        {
                            ID = new Guid("18e74e76-934f-4c06-b3ce-643c87c6dcfd"),
                            CreatedDate = new DateTime(2024, 3, 14, 3, 25, 48, 828, DateTimeKind.Local).AddTicks(2021),
                            IsApproved = false,
                            IsDeleted = false
                        },
                        new
                        {
                            ID = new Guid("b9066e07-91f7-44bb-a30b-7122aa190ecc"),
                            CreatedDate = new DateTime(2023, 7, 12, 16, 1, 40, 178, DateTimeKind.Local).AddTicks(3466),
                            IsApproved = false,
                            IsDeleted = false
                        },
                        new
                        {
                            ID = new Guid("eba86dbf-a17a-45e5-bcbf-6aa599af3be1"),
                            CreatedDate = new DateTime(2023, 5, 19, 16, 53, 38, 247, DateTimeKind.Local).AddTicks(8009),
                            IsApproved = false,
                            IsDeleted = false
                        },
                        new
                        {
                            ID = new Guid("80c7de02-40f8-4c82-bd90-212560c06949"),
                            CreatedDate = new DateTime(2024, 3, 9, 8, 3, 23, 331, DateTimeKind.Local).AddTicks(1311),
                            IsApproved = false,
                            IsDeleted = false
                        },
                        new
                        {
                            ID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2023, 8, 27, 20, 41, 27, 357, DateTimeKind.Local).AddTicks(2863),
                            IsApproved = false,
                            IsDeleted = false
                        },
                        new
                        {
                            ID = new Guid("34b395e8-4e60-4e13-9ea9-043c0f10852d"),
                            CreatedDate = new DateTime(2024, 1, 10, 2, 47, 14, 165, DateTimeKind.Local).AddTicks(6631),
                            IsApproved = false,
                            IsDeleted = false
                        },
                        new
                        {
                            ID = new Guid("4804fa42-5494-4cb0-8c17-f23731b0135d"),
                            CreatedDate = new DateTime(2024, 1, 28, 21, 8, 40, 131, DateTimeKind.Local).AddTicks(8251),
                            IsApproved = false,
                            IsDeleted = false
                        },
                        new
                        {
                            ID = new Guid("ef773918-5fff-4c25-84cd-f58b43442e21"),
                            CreatedDate = new DateTime(2024, 2, 4, 17, 4, 32, 247, DateTimeKind.Local).AddTicks(1861),
                            IsApproved = false,
                            IsDeleted = false
                        },
                        new
                        {
                            ID = new Guid("a5d13a52-2dc3-4167-8b8c-4c446844898b"),
                            CreatedDate = new DateTime(2024, 1, 29, 22, 27, 14, 741, DateTimeKind.Local).AddTicks(1692),
                            IsApproved = false,
                            IsDeleted = false
                        },
                        new
                        {
                            ID = new Guid("9072edf5-43e9-45d6-a04e-60e552ac8b57"),
                            CreatedDate = new DateTime(2023, 11, 4, 3, 23, 12, 450, DateTimeKind.Local).AddTicks(5287),
                            IsApproved = false,
                            IsDeleted = false
                        },
                        new
                        {
                            ID = new Guid("09118505-491b-46cd-b154-2f523567c531"),
                            CreatedDate = new DateTime(2024, 4, 25, 3, 13, 28, 678, DateTimeKind.Local).AddTicks(2019),
                            IsApproved = false,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("BtkApiProject.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = new Guid("dd868916-dcde-465f-a89c-313a24d230c6"),
                            CategoryID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2023, 11, 11, 20, 30, 32, 894, DateTimeKind.Local).AddTicks(5623),
                            Description = "Dolor blanditiis earum quia excepturi.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Incredible Cotton Car",
                            Price = 409.0
                        },
                        new
                        {
                            ID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CategoryID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2023, 5, 25, 3, 39, 8, 661, DateTimeKind.Local).AddTicks(6619),
                            Description = "Facilis in ut beatae est.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Tasty Plastic Soap",
                            Price = 113.0
                        },
                        new
                        {
                            ID = new Guid("18130346-e1b7-41d9-ba97-8e414d50457e"),
                            CategoryID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2023, 12, 10, 11, 20, 41, 669, DateTimeKind.Local).AddTicks(1612),
                            Description = "İste vero et nobis.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Ergonomic Wooden Shirt",
                            Price = 341.0
                        },
                        new
                        {
                            ID = new Guid("95b499c4-34a7-48a2-ac44-bc096de3fc66"),
                            CategoryID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2023, 12, 22, 4, 50, 12, 73, DateTimeKind.Local).AddTicks(1943),
                            Description = "Nulla voluptates rerum provident.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Tasty Cotton Cheese",
                            Price = 20.0
                        },
                        new
                        {
                            ID = new Guid("18e74e76-934f-4c06-b3ce-643c87c6dcfd"),
                            CategoryID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2024, 1, 28, 14, 35, 29, 716, DateTimeKind.Local).AddTicks(9232),
                            Description = "Et laudantium soluta nulla officia.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Handcrafted Frozen Bacon",
                            Price = 142.0
                        },
                        new
                        {
                            ID = new Guid("b9066e07-91f7-44bb-a30b-7122aa190ecc"),
                            CategoryID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2023, 7, 22, 22, 11, 36, 742, DateTimeKind.Local).AddTicks(3921),
                            Description = "Nemo inventore et quisquam veniam.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Ergonomic Granite Car",
                            Price = 349.0
                        },
                        new
                        {
                            ID = new Guid("eba86dbf-a17a-45e5-bcbf-6aa599af3be1"),
                            CategoryID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2023, 5, 24, 7, 27, 9, 363, DateTimeKind.Local).AddTicks(2607),
                            Description = "Rerum vel voluptate qui ipsum.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Licensed Soft Soap",
                            Price = 192.0
                        },
                        new
                        {
                            ID = new Guid("80c7de02-40f8-4c82-bd90-212560c06949"),
                            CategoryID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2023, 9, 19, 1, 48, 24, 588, DateTimeKind.Local).AddTicks(3678),
                            Description = "Vel fuga dignissimos dolore magni consequuntur.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Ergonomic Concrete Shirt",
                            Price = 54.0
                        },
                        new
                        {
                            ID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CategoryID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2023, 9, 2, 3, 53, 3, 439, DateTimeKind.Local).AddTicks(7048),
                            Description = "Molestias qui delectus explicabo provident at sit.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Sleek Concrete Chicken",
                            Price = 174.0
                        },
                        new
                        {
                            ID = new Guid("34b395e8-4e60-4e13-9ea9-043c0f10852d"),
                            CategoryID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2023, 7, 5, 14, 33, 30, 169, DateTimeKind.Local).AddTicks(8350),
                            Description = "Sunt voluptates sit quia voluptas.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Awesome Plastic Mouse",
                            Price = 412.0
                        },
                        new
                        {
                            ID = new Guid("4804fa42-5494-4cb0-8c17-f23731b0135d"),
                            CategoryID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2023, 7, 20, 4, 2, 14, 527, DateTimeKind.Local).AddTicks(4603),
                            Description = "Similique totam minus illum exercitationem.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Gorgeous Steel Shirt",
                            Price = 453.0
                        },
                        new
                        {
                            ID = new Guid("ef773918-5fff-4c25-84cd-f58b43442e21"),
                            CategoryID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2023, 6, 3, 21, 5, 23, 74, DateTimeKind.Local).AddTicks(5431),
                            Description = "İpsum neque nisi.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Handmade Rubber Soap",
                            Price = 154.0
                        },
                        new
                        {
                            ID = new Guid("a5d13a52-2dc3-4167-8b8c-4c446844898b"),
                            CategoryID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2023, 9, 4, 9, 0, 29, 186, DateTimeKind.Local).AddTicks(3646),
                            Description = "Est ex sint voluptas numquam.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Gorgeous Wooden Chicken",
                            Price = 485.0
                        },
                        new
                        {
                            ID = new Guid("9072edf5-43e9-45d6-a04e-60e552ac8b57"),
                            CategoryID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2024, 4, 26, 5, 49, 28, 588, DateTimeKind.Local).AddTicks(5722),
                            Description = "Optio eum corporis harum molestiae pariatur quis.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Handcrafted Metal Computer",
                            Price = 205.0
                        },
                        new
                        {
                            ID = new Guid("09118505-491b-46cd-b154-2f523567c531"),
                            CategoryID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2023, 12, 7, 5, 2, 52, 770, DateTimeKind.Local).AddTicks(9718),
                            Description = "Facere ut ea dolor a.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Tasty Steel Chips",
                            Price = 107.0
                        },
                        new
                        {
                            ID = new Guid("5e5589fe-77d8-49d2-9bbb-d1a42cba0bf1"),
                            CategoryID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2024, 3, 30, 21, 13, 42, 843, DateTimeKind.Local).AddTicks(1873),
                            Description = "Est aut atque ex cum.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Refined Wooden Chips",
                            Price = 487.0
                        },
                        new
                        {
                            ID = new Guid("fefc43b4-97a8-4713-8071-51930f12cb76"),
                            CategoryID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2023, 8, 4, 4, 30, 45, 655, DateTimeKind.Local).AddTicks(724),
                            Description = "Sapiente eos autem eum reiciendis rerum odit.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Small Steel Fish",
                            Price = 493.0
                        },
                        new
                        {
                            ID = new Guid("9a5c8eee-dfa0-4aee-8e39-c7f34bf24367"),
                            CategoryID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2024, 4, 27, 18, 51, 48, 911, DateTimeKind.Local).AddTicks(3746),
                            Description = "Soluta voluptatem a minus vel molestiae rem.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Fantastic Soft Shoes",
                            Price = 387.0
                        },
                        new
                        {
                            ID = new Guid("61d00226-a54f-43e4-b94f-ebd81c7acfb0"),
                            CategoryID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2023, 9, 24, 11, 16, 5, 968, DateTimeKind.Local).AddTicks(490),
                            Description = "Dolor est animi ipsum.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Incredible Fresh Cheese",
                            Price = 491.0
                        },
                        new
                        {
                            ID = new Guid("3e20bea6-3150-4551-8698-c93bcc384a09"),
                            CategoryID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2023, 7, 11, 15, 18, 44, 324, DateTimeKind.Local).AddTicks(3085),
                            Description = "Debitis dolores qui velit.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Unbranded Fresh Sausages",
                            Price = 135.0
                        },
                        new
                        {
                            ID = new Guid("32a39a39-0d03-4569-8908-8f0fbd483c65"),
                            CategoryID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2024, 3, 26, 3, 15, 41, 582, DateTimeKind.Local).AddTicks(8397),
                            Description = "Sit neque enim animi a recusandae.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Ergonomic Steel Ball",
                            Price = 380.0
                        },
                        new
                        {
                            ID = new Guid("54b58cfa-5b5e-4b2a-88cd-67e340ac758d"),
                            CategoryID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2024, 4, 21, 2, 55, 18, 559, DateTimeKind.Local).AddTicks(6495),
                            Description = "Eaque aspernatur assumenda ad aut similique sit commodi molestiae accusantium.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Fantastic Wooden Keyboard",
                            Price = 156.0
                        },
                        new
                        {
                            ID = new Guid("eac29877-cf98-49b2-b092-dabde42b829e"),
                            CategoryID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2023, 10, 28, 18, 54, 34, 564, DateTimeKind.Local).AddTicks(8856),
                            Description = "Qui at placeat perspiciatis.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Handcrafted Frozen Pizza",
                            Price = 154.0
                        },
                        new
                        {
                            ID = new Guid("0d210c85-5f4c-43a6-bcc2-a9546e99601b"),
                            CategoryID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2023, 7, 3, 20, 14, 7, 581, DateTimeKind.Local).AddTicks(3922),
                            Description = "İn rem unde.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Handmade Concrete Bike",
                            Price = 231.0
                        },
                        new
                        {
                            ID = new Guid("2993cc3b-48d8-4c3a-8662-9ae328688c9c"),
                            CategoryID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2023, 11, 24, 8, 37, 27, 645, DateTimeKind.Local).AddTicks(8302),
                            Description = "Odit commodi facere sint sint similique maiores officiis.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Small Granite Shirt",
                            Price = 382.0
                        },
                        new
                        {
                            ID = new Guid("8df428ba-1d69-45b8-8d40-40e235c957aa"),
                            CategoryID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2024, 1, 18, 15, 4, 36, 47, DateTimeKind.Local).AddTicks(6376),
                            Description = "Odit doloribus excepturi dolores omnis et unde.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Fantastic Concrete Ball",
                            Price = 371.0
                        },
                        new
                        {
                            ID = new Guid("3500e840-e254-4823-90fc-7a8789df67f6"),
                            CategoryID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2023, 8, 11, 17, 32, 31, 342, DateTimeKind.Local).AddTicks(4016),
                            Description = "Soluta consequatur consequatur sequi sed numquam voluptates quasi.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Handcrafted Frozen Pants",
                            Price = 481.0
                        },
                        new
                        {
                            ID = new Guid("866ea2a9-8721-4251-8022-ad988bd22b8c"),
                            CategoryID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2023, 9, 16, 18, 19, 58, 589, DateTimeKind.Local).AddTicks(6426),
                            Description = "Aut totam numquam quam.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Refined Rubber Pizza",
                            Price = 135.0
                        },
                        new
                        {
                            ID = new Guid("d11c7b91-2e92-4109-9d55-29adc4506f4f"),
                            CategoryID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2024, 2, 13, 20, 41, 11, 258, DateTimeKind.Local).AddTicks(6061),
                            Description = "Dolorem quis qui aperiam dolore.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Awesome Granite Keyboard",
                            Price = 477.0
                        },
                        new
                        {
                            ID = new Guid("dfbcdf14-bd61-4f63-847a-969b0c517f12"),
                            CategoryID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2023, 6, 15, 11, 33, 37, 878, DateTimeKind.Local).AddTicks(723),
                            Description = "Architecto libero autem et odio dolor quisquam.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Fantastic Concrete Fish",
                            Price = 445.0
                        },
                        new
                        {
                            ID = new Guid("1cbbd6f1-b054-44ed-805f-920a998aff90"),
                            CategoryID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2023, 8, 5, 9, 18, 15, 970, DateTimeKind.Local).AddTicks(289),
                            Description = "Nulla quidem vel in debitis.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Awesome Plastic Keyboard",
                            Price = 482.0
                        },
                        new
                        {
                            ID = new Guid("065bdc51-a618-45a1-90d7-567ef3843841"),
                            CategoryID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2024, 1, 12, 18, 19, 55, 660, DateTimeKind.Local).AddTicks(1609),
                            Description = "Asperiores aperiam molestiae sint voluptatem accusantium aperiam eum aliquam.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Rustic Fresh Sausages",
                            Price = 78.0
                        },
                        new
                        {
                            ID = new Guid("cd2460aa-cf15-4e44-954a-7f7c4c4e5a4e"),
                            CategoryID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2023, 11, 30, 19, 42, 56, 448, DateTimeKind.Local).AddTicks(9125),
                            Description = "Voluptatem et illo omnis aperiam.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Awesome Frozen Tuna",
                            Price = 325.0
                        },
                        new
                        {
                            ID = new Guid("57fb9bbb-aa3e-4791-94b7-80ea4883613b"),
                            CategoryID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2023, 8, 11, 1, 4, 1, 69, DateTimeKind.Local).AddTicks(413),
                            Description = "Eos id aut omnis.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Unbranded Wooden Towels",
                            Price = 43.0
                        },
                        new
                        {
                            ID = new Guid("388e1e08-a7bd-4552-97c8-b7c0f7b80f11"),
                            CategoryID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2024, 1, 16, 21, 30, 34, 407, DateTimeKind.Local).AddTicks(8562),
                            Description = "Qui quo voluptatem explicabo ipsam expedita eius.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Tasty Plastic Pizza",
                            Price = 279.0
                        },
                        new
                        {
                            ID = new Guid("7cd76b2b-197a-4ba2-98e1-430b8fd23038"),
                            CategoryID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2023, 8, 24, 17, 32, 2, 213, DateTimeKind.Local).AddTicks(8056),
                            Description = "Voluptatum autem quia sapiente dolorum sit molestiae.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Handcrafted Soft Soap",
                            Price = 422.0
                        },
                        new
                        {
                            ID = new Guid("d369c607-b40a-4375-a39b-53287b41aabb"),
                            CategoryID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2024, 3, 9, 12, 35, 26, 205, DateTimeKind.Local).AddTicks(5710),
                            Description = "Dignissimos aut repellendus labore.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Small Metal Bike",
                            Price = 171.0
                        },
                        new
                        {
                            ID = new Guid("61f5f234-13df-4b8e-8558-cccd9b84aab0"),
                            CategoryID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2023, 9, 7, 16, 48, 11, 382, DateTimeKind.Local).AddTicks(5774),
                            Description = "Atque qui quo consequatur corrupti voluptatem sunt incidunt non.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Small Cotton Cheese",
                            Price = 66.0
                        },
                        new
                        {
                            ID = new Guid("96b78027-3570-45bd-8d74-cdaa23c181b8"),
                            CategoryID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2023, 10, 5, 6, 28, 43, 456, DateTimeKind.Local).AddTicks(6425),
                            Description = "Eum voluptates placeat.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Generic Rubber Shoes",
                            Price = 277.0
                        },
                        new
                        {
                            ID = new Guid("f2cd9efc-1bdb-48ad-ad51-13bb4daff119"),
                            CategoryID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2023, 11, 22, 21, 44, 54, 642, DateTimeKind.Local).AddTicks(1999),
                            Description = "Eaque nam corporis.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Gorgeous Soft Chips",
                            Price = 127.0
                        },
                        new
                        {
                            ID = new Guid("c66915b3-d9f8-4bb6-bd46-828e5a946a61"),
                            CategoryID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2024, 4, 26, 19, 8, 4, 897, DateTimeKind.Local).AddTicks(5793),
                            Description = "Eligendi nostrum nesciunt ratione ea dolorem.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Handmade Wooden Pizza",
                            Price = 492.0
                        },
                        new
                        {
                            ID = new Guid("6d776c03-bd8a-4ed4-965d-92bd5d196380"),
                            CategoryID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2024, 2, 6, 1, 46, 48, 754, DateTimeKind.Local).AddTicks(5195),
                            Description = "Sint blanditiis voluptates est vero magnam autem.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Refined Granite Soap",
                            Price = 288.0
                        },
                        new
                        {
                            ID = new Guid("99bd8cd0-f4c4-403a-b678-a3c233ed9f7e"),
                            CategoryID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2023, 9, 16, 2, 27, 51, 878, DateTimeKind.Local).AddTicks(6309),
                            Description = "Quae aliquam soluta sint iste dolor et sed est.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Unbranded Plastic Tuna",
                            Price = 439.0
                        },
                        new
                        {
                            ID = new Guid("5f6ac016-ec06-4c35-8f74-164c3e0724d3"),
                            CategoryID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2024, 3, 27, 18, 0, 58, 146, DateTimeKind.Local).AddTicks(2405),
                            Description = "Amet soluta exercitationem debitis.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Refined Concrete Chair",
                            Price = 157.0
                        },
                        new
                        {
                            ID = new Guid("cb35d17f-0bdb-4237-9cd9-27e6f436cdc4"),
                            CategoryID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2023, 9, 16, 22, 25, 24, 118, DateTimeKind.Local).AddTicks(2370),
                            Description = "Et ut consequatur ducimus delectus.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Refined Cotton Shirt",
                            Price = 26.0
                        },
                        new
                        {
                            ID = new Guid("65e02ef9-a536-4c6a-9f18-1c6dd9af4fd6"),
                            CategoryID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2023, 6, 25, 16, 9, 6, 228, DateTimeKind.Local).AddTicks(7659),
                            Description = "Nam aut suscipit.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Generic Soft Chicken",
                            Price = 252.0
                        },
                        new
                        {
                            ID = new Guid("35677582-d7f7-4230-ab73-35d5fdc19a1b"),
                            CategoryID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2023, 12, 8, 7, 44, 20, 960, DateTimeKind.Local).AddTicks(5258),
                            Description = "Autem dolorem nam cupiditate aut repudiandae et praesentium repellendus praesentium.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Refined Rubber Pants",
                            Price = 163.0
                        },
                        new
                        {
                            ID = new Guid("de22d097-5f6c-42bc-947d-5ada70509533"),
                            CategoryID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2023, 9, 15, 2, 47, 40, 420, DateTimeKind.Local).AddTicks(4580),
                            Description = "Rerum totam cupiditate iure.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Intelligent Wooden Bacon",
                            Price = 393.0
                        },
                        new
                        {
                            ID = new Guid("8c4b66b6-8fea-4330-be08-5e548e473a7b"),
                            CategoryID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2024, 4, 1, 7, 30, 2, 817, DateTimeKind.Local).AddTicks(970),
                            Description = "Aliquid neque esse.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Incredible Plastic Pants",
                            Price = 28.0
                        },
                        new
                        {
                            ID = new Guid("7532d41d-4ec0-4c29-9864-25d1e936ccec"),
                            CategoryID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2024, 4, 27, 0, 0, 29, 935, DateTimeKind.Local).AddTicks(5006),
                            Description = "Expedita quisquam totam ut et voluptatibus quos.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Rustic Soft Tuna",
                            Price = 452.0
                        });
                });

            modelBuilder.Entity("BtkApiProject.Domain.Entities.ProductDetail", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProductID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("ProductID")
                        .IsUnique();

                    b.ToTable("ProductDetails");

                    b.HasData(
                        new
                        {
                            ID = new Guid("dd868916-dcde-465f-a89c-313a24d230c6"),
                            CreatedDate = new DateTime(2023, 11, 17, 10, 41, 40, 427, DateTimeKind.Local).AddTicks(2577),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("dd868916-dcde-465f-a89c-313a24d230c6"),
                            Quantity = 5
                        },
                        new
                        {
                            ID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2023, 9, 27, 1, 7, 19, 893, DateTimeKind.Local).AddTicks(1290),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            Quantity = 1
                        },
                        new
                        {
                            ID = new Guid("18130346-e1b7-41d9-ba97-8e414d50457e"),
                            CreatedDate = new DateTime(2023, 9, 14, 5, 23, 38, 201, DateTimeKind.Local).AddTicks(7249),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("18130346-e1b7-41d9-ba97-8e414d50457e"),
                            Quantity = 0
                        },
                        new
                        {
                            ID = new Guid("95b499c4-34a7-48a2-ac44-bc096de3fc66"),
                            CreatedDate = new DateTime(2024, 1, 28, 9, 40, 23, 986, DateTimeKind.Local).AddTicks(4322),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("95b499c4-34a7-48a2-ac44-bc096de3fc66"),
                            Quantity = 8
                        },
                        new
                        {
                            ID = new Guid("18e74e76-934f-4c06-b3ce-643c87c6dcfd"),
                            CreatedDate = new DateTime(2023, 12, 23, 8, 50, 15, 796, DateTimeKind.Local).AddTicks(1770),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("18e74e76-934f-4c06-b3ce-643c87c6dcfd"),
                            Quantity = 25
                        },
                        new
                        {
                            ID = new Guid("b9066e07-91f7-44bb-a30b-7122aa190ecc"),
                            CreatedDate = new DateTime(2023, 10, 29, 5, 27, 23, 958, DateTimeKind.Local).AddTicks(9554),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("b9066e07-91f7-44bb-a30b-7122aa190ecc"),
                            Quantity = 36
                        },
                        new
                        {
                            ID = new Guid("eba86dbf-a17a-45e5-bcbf-6aa599af3be1"),
                            CreatedDate = new DateTime(2023, 7, 9, 2, 47, 8, 487, DateTimeKind.Local).AddTicks(8953),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("eba86dbf-a17a-45e5-bcbf-6aa599af3be1"),
                            Quantity = 25
                        },
                        new
                        {
                            ID = new Guid("80c7de02-40f8-4c82-bd90-212560c06949"),
                            CreatedDate = new DateTime(2024, 4, 23, 14, 2, 21, 34, DateTimeKind.Local).AddTicks(5872),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("80c7de02-40f8-4c82-bd90-212560c06949"),
                            Quantity = 31
                        },
                        new
                        {
                            ID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2023, 12, 23, 22, 50, 56, 530, DateTimeKind.Local).AddTicks(1892),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            Quantity = 30
                        },
                        new
                        {
                            ID = new Guid("34b395e8-4e60-4e13-9ea9-043c0f10852d"),
                            CreatedDate = new DateTime(2024, 1, 15, 16, 21, 30, 702, DateTimeKind.Local).AddTicks(6936),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("34b395e8-4e60-4e13-9ea9-043c0f10852d"),
                            Quantity = 46
                        },
                        new
                        {
                            ID = new Guid("4804fa42-5494-4cb0-8c17-f23731b0135d"),
                            CreatedDate = new DateTime(2023, 7, 16, 14, 35, 15, 128, DateTimeKind.Local).AddTicks(7626),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("4804fa42-5494-4cb0-8c17-f23731b0135d"),
                            Quantity = 36
                        },
                        new
                        {
                            ID = new Guid("ef773918-5fff-4c25-84cd-f58b43442e21"),
                            CreatedDate = new DateTime(2024, 2, 11, 13, 42, 10, 836, DateTimeKind.Local).AddTicks(3899),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("ef773918-5fff-4c25-84cd-f58b43442e21"),
                            Quantity = 15
                        },
                        new
                        {
                            ID = new Guid("a5d13a52-2dc3-4167-8b8c-4c446844898b"),
                            CreatedDate = new DateTime(2023, 6, 18, 22, 37, 34, 939, DateTimeKind.Local).AddTicks(1864),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("a5d13a52-2dc3-4167-8b8c-4c446844898b"),
                            Quantity = 18
                        },
                        new
                        {
                            ID = new Guid("9072edf5-43e9-45d6-a04e-60e552ac8b57"),
                            CreatedDate = new DateTime(2024, 1, 27, 23, 51, 30, 692, DateTimeKind.Local).AddTicks(9681),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("9072edf5-43e9-45d6-a04e-60e552ac8b57"),
                            Quantity = 9
                        },
                        new
                        {
                            ID = new Guid("09118505-491b-46cd-b154-2f523567c531"),
                            CreatedDate = new DateTime(2023, 6, 9, 3, 1, 14, 774, DateTimeKind.Local).AddTicks(8917),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("09118505-491b-46cd-b154-2f523567c531"),
                            Quantity = 5
                        },
                        new
                        {
                            ID = new Guid("5e5589fe-77d8-49d2-9bbb-d1a42cba0bf1"),
                            CreatedDate = new DateTime(2023, 8, 19, 0, 26, 0, 97, DateTimeKind.Local).AddTicks(7966),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("5e5589fe-77d8-49d2-9bbb-d1a42cba0bf1"),
                            Quantity = 3
                        },
                        new
                        {
                            ID = new Guid("fefc43b4-97a8-4713-8071-51930f12cb76"),
                            CreatedDate = new DateTime(2023, 8, 28, 4, 33, 38, 214, DateTimeKind.Local).AddTicks(9190),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("fefc43b4-97a8-4713-8071-51930f12cb76"),
                            Quantity = 49
                        },
                        new
                        {
                            ID = new Guid("9a5c8eee-dfa0-4aee-8e39-c7f34bf24367"),
                            CreatedDate = new DateTime(2024, 1, 26, 13, 3, 8, 382, DateTimeKind.Local).AddTicks(9912),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("9a5c8eee-dfa0-4aee-8e39-c7f34bf24367"),
                            Quantity = 8
                        },
                        new
                        {
                            ID = new Guid("61d00226-a54f-43e4-b94f-ebd81c7acfb0"),
                            CreatedDate = new DateTime(2024, 2, 14, 4, 24, 59, 860, DateTimeKind.Local).AddTicks(116),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("61d00226-a54f-43e4-b94f-ebd81c7acfb0"),
                            Quantity = 9
                        },
                        new
                        {
                            ID = new Guid("3e20bea6-3150-4551-8698-c93bcc384a09"),
                            CreatedDate = new DateTime(2023, 8, 8, 7, 8, 56, 443, DateTimeKind.Local).AddTicks(8487),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("3e20bea6-3150-4551-8698-c93bcc384a09"),
                            Quantity = 13
                        },
                        new
                        {
                            ID = new Guid("32a39a39-0d03-4569-8908-8f0fbd483c65"),
                            CreatedDate = new DateTime(2023, 9, 17, 9, 55, 46, 700, DateTimeKind.Local).AddTicks(9918),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("32a39a39-0d03-4569-8908-8f0fbd483c65"),
                            Quantity = 10
                        },
                        new
                        {
                            ID = new Guid("54b58cfa-5b5e-4b2a-88cd-67e340ac758d"),
                            CreatedDate = new DateTime(2023, 8, 26, 1, 7, 33, 230, DateTimeKind.Local).AddTicks(196),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("54b58cfa-5b5e-4b2a-88cd-67e340ac758d"),
                            Quantity = 20
                        },
                        new
                        {
                            ID = new Guid("eac29877-cf98-49b2-b092-dabde42b829e"),
                            CreatedDate = new DateTime(2023, 5, 8, 19, 58, 51, 14, DateTimeKind.Local).AddTicks(211),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("eac29877-cf98-49b2-b092-dabde42b829e"),
                            Quantity = 49
                        },
                        new
                        {
                            ID = new Guid("0d210c85-5f4c-43a6-bcc2-a9546e99601b"),
                            CreatedDate = new DateTime(2024, 4, 14, 22, 53, 25, 670, DateTimeKind.Local).AddTicks(8944),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("0d210c85-5f4c-43a6-bcc2-a9546e99601b"),
                            Quantity = 43
                        },
                        new
                        {
                            ID = new Guid("2993cc3b-48d8-4c3a-8662-9ae328688c9c"),
                            CreatedDate = new DateTime(2023, 11, 10, 18, 41, 24, 722, DateTimeKind.Local).AddTicks(712),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("2993cc3b-48d8-4c3a-8662-9ae328688c9c"),
                            Quantity = 18
                        },
                        new
                        {
                            ID = new Guid("8df428ba-1d69-45b8-8d40-40e235c957aa"),
                            CreatedDate = new DateTime(2024, 2, 16, 5, 30, 18, 416, DateTimeKind.Local).AddTicks(2851),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("8df428ba-1d69-45b8-8d40-40e235c957aa"),
                            Quantity = 6
                        },
                        new
                        {
                            ID = new Guid("3500e840-e254-4823-90fc-7a8789df67f6"),
                            CreatedDate = new DateTime(2023, 10, 14, 14, 55, 39, 471, DateTimeKind.Local).AddTicks(5138),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("3500e840-e254-4823-90fc-7a8789df67f6"),
                            Quantity = 13
                        },
                        new
                        {
                            ID = new Guid("866ea2a9-8721-4251-8022-ad988bd22b8c"),
                            CreatedDate = new DateTime(2023, 12, 14, 10, 18, 31, 325, DateTimeKind.Local).AddTicks(1194),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("866ea2a9-8721-4251-8022-ad988bd22b8c"),
                            Quantity = 41
                        },
                        new
                        {
                            ID = new Guid("d11c7b91-2e92-4109-9d55-29adc4506f4f"),
                            CreatedDate = new DateTime(2023, 10, 9, 10, 18, 6, 440, DateTimeKind.Local).AddTicks(3544),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("d11c7b91-2e92-4109-9d55-29adc4506f4f"),
                            Quantity = 30
                        },
                        new
                        {
                            ID = new Guid("dfbcdf14-bd61-4f63-847a-969b0c517f12"),
                            CreatedDate = new DateTime(2023, 12, 11, 22, 37, 54, 410, DateTimeKind.Local).AddTicks(6599),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("dfbcdf14-bd61-4f63-847a-969b0c517f12"),
                            Quantity = 3
                        },
                        new
                        {
                            ID = new Guid("1cbbd6f1-b054-44ed-805f-920a998aff90"),
                            CreatedDate = new DateTime(2023, 10, 11, 23, 9, 58, 684, DateTimeKind.Local).AddTicks(8022),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("1cbbd6f1-b054-44ed-805f-920a998aff90"),
                            Quantity = 4
                        },
                        new
                        {
                            ID = new Guid("065bdc51-a618-45a1-90d7-567ef3843841"),
                            CreatedDate = new DateTime(2024, 3, 26, 9, 44, 21, 91, DateTimeKind.Local).AddTicks(9930),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("065bdc51-a618-45a1-90d7-567ef3843841"),
                            Quantity = 45
                        },
                        new
                        {
                            ID = new Guid("cd2460aa-cf15-4e44-954a-7f7c4c4e5a4e"),
                            CreatedDate = new DateTime(2023, 12, 9, 22, 34, 31, 193, DateTimeKind.Local).AddTicks(2258),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("cd2460aa-cf15-4e44-954a-7f7c4c4e5a4e"),
                            Quantity = 25
                        },
                        new
                        {
                            ID = new Guid("57fb9bbb-aa3e-4791-94b7-80ea4883613b"),
                            CreatedDate = new DateTime(2023, 9, 9, 19, 22, 15, 408, DateTimeKind.Local).AddTicks(4284),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("57fb9bbb-aa3e-4791-94b7-80ea4883613b"),
                            Quantity = 19
                        },
                        new
                        {
                            ID = new Guid("388e1e08-a7bd-4552-97c8-b7c0f7b80f11"),
                            CreatedDate = new DateTime(2024, 3, 10, 4, 43, 54, 679, DateTimeKind.Local).AddTicks(1902),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("388e1e08-a7bd-4552-97c8-b7c0f7b80f11"),
                            Quantity = 32
                        },
                        new
                        {
                            ID = new Guid("7cd76b2b-197a-4ba2-98e1-430b8fd23038"),
                            CreatedDate = new DateTime(2023, 6, 26, 7, 13, 51, 999, DateTimeKind.Local).AddTicks(408),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("7cd76b2b-197a-4ba2-98e1-430b8fd23038"),
                            Quantity = 0
                        },
                        new
                        {
                            ID = new Guid("d369c607-b40a-4375-a39b-53287b41aabb"),
                            CreatedDate = new DateTime(2023, 12, 30, 10, 11, 37, 822, DateTimeKind.Local).AddTicks(8666),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("d369c607-b40a-4375-a39b-53287b41aabb"),
                            Quantity = 12
                        },
                        new
                        {
                            ID = new Guid("61f5f234-13df-4b8e-8558-cccd9b84aab0"),
                            CreatedDate = new DateTime(2023, 11, 5, 23, 12, 55, 990, DateTimeKind.Local).AddTicks(6405),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("61f5f234-13df-4b8e-8558-cccd9b84aab0"),
                            Quantity = 26
                        },
                        new
                        {
                            ID = new Guid("96b78027-3570-45bd-8d74-cdaa23c181b8"),
                            CreatedDate = new DateTime(2023, 11, 2, 16, 2, 16, 683, DateTimeKind.Local).AddTicks(5550),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("96b78027-3570-45bd-8d74-cdaa23c181b8"),
                            Quantity = 25
                        },
                        new
                        {
                            ID = new Guid("f2cd9efc-1bdb-48ad-ad51-13bb4daff119"),
                            CreatedDate = new DateTime(2023, 10, 27, 17, 44, 43, 148, DateTimeKind.Local).AddTicks(9106),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("f2cd9efc-1bdb-48ad-ad51-13bb4daff119"),
                            Quantity = 6
                        },
                        new
                        {
                            ID = new Guid("c66915b3-d9f8-4bb6-bd46-828e5a946a61"),
                            CreatedDate = new DateTime(2023, 6, 1, 9, 54, 46, 966, DateTimeKind.Local).AddTicks(9909),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("c66915b3-d9f8-4bb6-bd46-828e5a946a61"),
                            Quantity = 2
                        },
                        new
                        {
                            ID = new Guid("6d776c03-bd8a-4ed4-965d-92bd5d196380"),
                            CreatedDate = new DateTime(2024, 1, 26, 0, 20, 15, 436, DateTimeKind.Local).AddTicks(9400),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("6d776c03-bd8a-4ed4-965d-92bd5d196380"),
                            Quantity = 22
                        },
                        new
                        {
                            ID = new Guid("99bd8cd0-f4c4-403a-b678-a3c233ed9f7e"),
                            CreatedDate = new DateTime(2024, 4, 15, 7, 10, 1, 412, DateTimeKind.Local).AddTicks(7056),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("99bd8cd0-f4c4-403a-b678-a3c233ed9f7e"),
                            Quantity = 49
                        },
                        new
                        {
                            ID = new Guid("5f6ac016-ec06-4c35-8f74-164c3e0724d3"),
                            CreatedDate = new DateTime(2023, 7, 23, 10, 35, 55, 936, DateTimeKind.Local).AddTicks(4152),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("5f6ac016-ec06-4c35-8f74-164c3e0724d3"),
                            Quantity = 35
                        },
                        new
                        {
                            ID = new Guid("cb35d17f-0bdb-4237-9cd9-27e6f436cdc4"),
                            CreatedDate = new DateTime(2024, 2, 6, 23, 31, 12, 699, DateTimeKind.Local).AddTicks(9196),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("cb35d17f-0bdb-4237-9cd9-27e6f436cdc4"),
                            Quantity = 13
                        },
                        new
                        {
                            ID = new Guid("65e02ef9-a536-4c6a-9f18-1c6dd9af4fd6"),
                            CreatedDate = new DateTime(2024, 2, 29, 13, 26, 23, 813, DateTimeKind.Local).AddTicks(1851),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("65e02ef9-a536-4c6a-9f18-1c6dd9af4fd6"),
                            Quantity = 39
                        },
                        new
                        {
                            ID = new Guid("35677582-d7f7-4230-ab73-35d5fdc19a1b"),
                            CreatedDate = new DateTime(2023, 9, 22, 8, 55, 34, 540, DateTimeKind.Local).AddTicks(13),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("35677582-d7f7-4230-ab73-35d5fdc19a1b"),
                            Quantity = 23
                        },
                        new
                        {
                            ID = new Guid("de22d097-5f6c-42bc-947d-5ada70509533"),
                            CreatedDate = new DateTime(2024, 3, 3, 9, 55, 19, 835, DateTimeKind.Local).AddTicks(2752),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("de22d097-5f6c-42bc-947d-5ada70509533"),
                            Quantity = 35
                        },
                        new
                        {
                            ID = new Guid("8c4b66b6-8fea-4330-be08-5e548e473a7b"),
                            CreatedDate = new DateTime(2023, 9, 3, 18, 31, 39, 307, DateTimeKind.Local).AddTicks(491),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("8c4b66b6-8fea-4330-be08-5e548e473a7b"),
                            Quantity = 33
                        },
                        new
                        {
                            ID = new Guid("7532d41d-4ec0-4c29-9864-25d1e936ccec"),
                            CreatedDate = new DateTime(2024, 4, 10, 6, 43, 18, 994, DateTimeKind.Local).AddTicks(1074),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("7532d41d-4ec0-4c29-9864-25d1e936ccec"),
                            Quantity = 12
                        });
                });

            modelBuilder.Entity("BtkApiProject.Domain.Entities.Joins.OrderProduct", b =>
                {
                    b.HasOne("BtkApiProject.Domain.Entities.Order", "Order")
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BtkApiProject.Domain.Entities.Product", "Product")
                        .WithMany("OrderProducts")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BtkApiProject.Domain.Entities.Product", b =>
                {
                    b.HasOne("BtkApiProject.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BtkApiProject.Domain.Entities.ProductDetail", b =>
                {
                    b.HasOne("BtkApiProject.Domain.Entities.Product", "Product")
                        .WithOne("ProductDetail")
                        .HasForeignKey("BtkApiProject.Domain.Entities.ProductDetail", "ProductID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BtkApiProject.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BtkApiProject.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("BtkApiProject.Domain.Entities.Product", b =>
                {
                    b.Navigation("OrderProducts");

                    b.Navigation("ProductDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
