// <auto-generated />
using System;
using BtkApiProject.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BtkApiProject.Persistence.Migrations
{
    [DbContext(typeof(CustomDbContext))]
    [Migration("20240420142432_mig1")]
    partial class mig1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BtkApiProject.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = new Guid("dd868916-dcde-465f-a89c-313a24d230c6"),
                            CreatedDate = new DateTime(2023, 10, 24, 22, 25, 19, 358, DateTimeKind.Local).AddTicks(7304),
                            Description = "Qui düşünüyor et voluptate gördüm ut domates.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Kitap"
                        },
                        new
                        {
                            ID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2023, 8, 4, 0, 42, 23, 158, DateTimeKind.Local).AddTicks(550),
                            Description = "Quasi çıktılar eaque.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Elektronik"
                        },
                        new
                        {
                            ID = new Guid("18130346-e1b7-41d9-ba97-8e414d50457e"),
                            CreatedDate = new DateTime(2023, 10, 3, 4, 16, 23, 874, DateTimeKind.Local).AddTicks(1776),
                            Description = "Çorba totam doloremque gördüm layıkıyla molestiae nesciunt.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Film"
                        },
                        new
                        {
                            ID = new Guid("95b499c4-34a7-48a2-ac44-bc096de3fc66"),
                            CreatedDate = new DateTime(2023, 12, 31, 5, 50, 1, 162, DateTimeKind.Local).AddTicks(6626),
                            Description = "Voluptatem magni voluptatem eve kulu telefonu ışık ea ki aut.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Spor"
                        },
                        new
                        {
                            ID = new Guid("18e74e76-934f-4c06-b3ce-643c87c6dcfd"),
                            CreatedDate = new DateTime(2024, 4, 13, 13, 4, 4, 734, DateTimeKind.Local).AddTicks(1438),
                            Description = "Gülüyorum quis değirmeni sit ona yaptı gül.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Giyim"
                        },
                        new
                        {
                            ID = new Guid("b9066e07-91f7-44bb-a30b-7122aa190ecc"),
                            CreatedDate = new DateTime(2023, 8, 13, 10, 1, 37, 850, DateTimeKind.Local).AddTicks(5769),
                            Description = "Architecto blanditiis sıradanlıktan.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Aksesuar"
                        },
                        new
                        {
                            ID = new Guid("eba86dbf-a17a-45e5-bcbf-6aa599af3be1"),
                            CreatedDate = new DateTime(2024, 3, 15, 5, 52, 33, 595, DateTimeKind.Local).AddTicks(4450),
                            Description = "Quasi quis laudantium alias autem.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Mobilya"
                        },
                        new
                        {
                            ID = new Guid("80c7de02-40f8-4c82-bd90-212560c06949"),
                            CreatedDate = new DateTime(2023, 9, 29, 3, 38, 49, 416, DateTimeKind.Local).AddTicks(9825),
                            Description = "Makinesi ama qui nesciunt consequatur qui cezbelendi makinesi quia tv.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Oyun"
                        },
                        new
                        {
                            ID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2023, 9, 5, 10, 20, 9, 552, DateTimeKind.Local).AddTicks(3244),
                            Description = "Koyun patlıcan sıla et bilgisayarı sit cezbelendi makinesi.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Sanat"
                        },
                        new
                        {
                            ID = new Guid("34b395e8-4e60-4e13-9ea9-043c0f10852d"),
                            CreatedDate = new DateTime(2023, 8, 4, 18, 40, 35, 812, DateTimeKind.Local).AddTicks(4530),
                            Description = "Dolore biber ut ullam exercitationem kulu quaerat.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Müzik"
                        });
                });

            modelBuilder.Entity("BtkApiProject.Domain.Entities.Joins.OrderProduct", b =>
                {
                    b.Property<Guid>("OrderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OrderID", "ProductID");

                    b.HasIndex("ProductID");

                    b.ToTable("OrderProduct");

                    b.HasData(
                        new
                        {
                            OrderID = new Guid("dd868916-dcde-465f-a89c-313a24d230c6"),
                            ProductID = new Guid("dd868916-dcde-465f-a89c-313a24d230c6")
                        },
                        new
                        {
                            OrderID = new Guid("dd868916-dcde-465f-a89c-313a24d230c6"),
                            ProductID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b")
                        },
                        new
                        {
                            OrderID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            ProductID = new Guid("18130346-e1b7-41d9-ba97-8e414d50457e")
                        },
                        new
                        {
                            OrderID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            ProductID = new Guid("95b499c4-34a7-48a2-ac44-bc096de3fc66")
                        },
                        new
                        {
                            OrderID = new Guid("18130346-e1b7-41d9-ba97-8e414d50457e"),
                            ProductID = new Guid("18e74e76-934f-4c06-b3ce-643c87c6dcfd")
                        },
                        new
                        {
                            OrderID = new Guid("18130346-e1b7-41d9-ba97-8e414d50457e"),
                            ProductID = new Guid("b9066e07-91f7-44bb-a30b-7122aa190ecc")
                        },
                        new
                        {
                            OrderID = new Guid("95b499c4-34a7-48a2-ac44-bc096de3fc66"),
                            ProductID = new Guid("eba86dbf-a17a-45e5-bcbf-6aa599af3be1")
                        },
                        new
                        {
                            OrderID = new Guid("95b499c4-34a7-48a2-ac44-bc096de3fc66"),
                            ProductID = new Guid("80c7de02-40f8-4c82-bd90-212560c06949")
                        },
                        new
                        {
                            OrderID = new Guid("18e74e76-934f-4c06-b3ce-643c87c6dcfd"),
                            ProductID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b")
                        },
                        new
                        {
                            OrderID = new Guid("18e74e76-934f-4c06-b3ce-643c87c6dcfd"),
                            ProductID = new Guid("34b395e8-4e60-4e13-9ea9-043c0f10852d")
                        },
                        new
                        {
                            OrderID = new Guid("b9066e07-91f7-44bb-a30b-7122aa190ecc"),
                            ProductID = new Guid("4804fa42-5494-4cb0-8c17-f23731b0135d")
                        },
                        new
                        {
                            OrderID = new Guid("b9066e07-91f7-44bb-a30b-7122aa190ecc"),
                            ProductID = new Guid("ef773918-5fff-4c25-84cd-f58b43442e21")
                        },
                        new
                        {
                            OrderID = new Guid("eba86dbf-a17a-45e5-bcbf-6aa599af3be1"),
                            ProductID = new Guid("a5d13a52-2dc3-4167-8b8c-4c446844898b")
                        },
                        new
                        {
                            OrderID = new Guid("eba86dbf-a17a-45e5-bcbf-6aa599af3be1"),
                            ProductID = new Guid("9072edf5-43e9-45d6-a04e-60e552ac8b57")
                        },
                        new
                        {
                            OrderID = new Guid("80c7de02-40f8-4c82-bd90-212560c06949"),
                            ProductID = new Guid("09118505-491b-46cd-b154-2f523567c531")
                        },
                        new
                        {
                            OrderID = new Guid("80c7de02-40f8-4c82-bd90-212560c06949"),
                            ProductID = new Guid("5e5589fe-77d8-49d2-9bbb-d1a42cba0bf1")
                        },
                        new
                        {
                            OrderID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            ProductID = new Guid("fefc43b4-97a8-4713-8071-51930f12cb76")
                        },
                        new
                        {
                            OrderID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            ProductID = new Guid("9a5c8eee-dfa0-4aee-8e39-c7f34bf24367")
                        },
                        new
                        {
                            OrderID = new Guid("34b395e8-4e60-4e13-9ea9-043c0f10852d"),
                            ProductID = new Guid("61d00226-a54f-43e4-b94f-ebd81c7acfb0")
                        },
                        new
                        {
                            OrderID = new Guid("34b395e8-4e60-4e13-9ea9-043c0f10852d"),
                            ProductID = new Guid("3e20bea6-3150-4551-8698-c93bcc384a09")
                        },
                        new
                        {
                            OrderID = new Guid("4804fa42-5494-4cb0-8c17-f23731b0135d"),
                            ProductID = new Guid("32a39a39-0d03-4569-8908-8f0fbd483c65")
                        },
                        new
                        {
                            OrderID = new Guid("4804fa42-5494-4cb0-8c17-f23731b0135d"),
                            ProductID = new Guid("54b58cfa-5b5e-4b2a-88cd-67e340ac758d")
                        },
                        new
                        {
                            OrderID = new Guid("ef773918-5fff-4c25-84cd-f58b43442e21"),
                            ProductID = new Guid("eac29877-cf98-49b2-b092-dabde42b829e")
                        },
                        new
                        {
                            OrderID = new Guid("ef773918-5fff-4c25-84cd-f58b43442e21"),
                            ProductID = new Guid("0d210c85-5f4c-43a6-bcc2-a9546e99601b")
                        },
                        new
                        {
                            OrderID = new Guid("a5d13a52-2dc3-4167-8b8c-4c446844898b"),
                            ProductID = new Guid("2993cc3b-48d8-4c3a-8662-9ae328688c9c")
                        },
                        new
                        {
                            OrderID = new Guid("a5d13a52-2dc3-4167-8b8c-4c446844898b"),
                            ProductID = new Guid("8df428ba-1d69-45b8-8d40-40e235c957aa")
                        },
                        new
                        {
                            OrderID = new Guid("9072edf5-43e9-45d6-a04e-60e552ac8b57"),
                            ProductID = new Guid("3500e840-e254-4823-90fc-7a8789df67f6")
                        },
                        new
                        {
                            OrderID = new Guid("9072edf5-43e9-45d6-a04e-60e552ac8b57"),
                            ProductID = new Guid("866ea2a9-8721-4251-8022-ad988bd22b8c")
                        },
                        new
                        {
                            OrderID = new Guid("09118505-491b-46cd-b154-2f523567c531"),
                            ProductID = new Guid("d11c7b91-2e92-4109-9d55-29adc4506f4f")
                        },
                        new
                        {
                            OrderID = new Guid("09118505-491b-46cd-b154-2f523567c531"),
                            ProductID = new Guid("dfbcdf14-bd61-4f63-847a-969b0c517f12")
                        });
                });

            modelBuilder.Entity("BtkApiProject.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            ID = new Guid("dd868916-dcde-465f-a89c-313a24d230c6"),
                            CreatedDate = new DateTime(2023, 11, 6, 13, 22, 14, 650, DateTimeKind.Local).AddTicks(1149),
                            IsApproved = false,
                            IsDeleted = false
                        },
                        new
                        {
                            ID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2023, 9, 18, 18, 37, 50, 650, DateTimeKind.Local).AddTicks(2497),
                            IsApproved = false,
                            IsDeleted = false
                        },
                        new
                        {
                            ID = new Guid("18130346-e1b7-41d9-ba97-8e414d50457e"),
                            CreatedDate = new DateTime(2024, 2, 29, 17, 6, 54, 0, DateTimeKind.Local).AddTicks(3796),
                            IsApproved = false,
                            IsDeleted = false
                        },
                        new
                        {
                            ID = new Guid("95b499c4-34a7-48a2-ac44-bc096de3fc66"),
                            CreatedDate = new DateTime(2023, 8, 2, 5, 44, 23, 122, DateTimeKind.Local).AddTicks(1078),
                            IsApproved = false,
                            IsDeleted = false
                        },
                        new
                        {
                            ID = new Guid("18e74e76-934f-4c06-b3ce-643c87c6dcfd"),
                            CreatedDate = new DateTime(2023, 12, 2, 12, 33, 31, 8, DateTimeKind.Local).AddTicks(8033),
                            IsApproved = false,
                            IsDeleted = false
                        },
                        new
                        {
                            ID = new Guid("b9066e07-91f7-44bb-a30b-7122aa190ecc"),
                            CreatedDate = new DateTime(2024, 4, 10, 2, 2, 14, 119, DateTimeKind.Local).AddTicks(9737),
                            IsApproved = false,
                            IsDeleted = false
                        },
                        new
                        {
                            ID = new Guid("eba86dbf-a17a-45e5-bcbf-6aa599af3be1"),
                            CreatedDate = new DateTime(2023, 9, 24, 5, 53, 11, 806, DateTimeKind.Local).AddTicks(1471),
                            IsApproved = false,
                            IsDeleted = false
                        },
                        new
                        {
                            ID = new Guid("80c7de02-40f8-4c82-bd90-212560c06949"),
                            CreatedDate = new DateTime(2024, 2, 2, 15, 20, 31, 667, DateTimeKind.Local).AddTicks(2369),
                            IsApproved = false,
                            IsDeleted = false
                        },
                        new
                        {
                            ID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2023, 11, 14, 2, 23, 7, 554, DateTimeKind.Local).AddTicks(8928),
                            IsApproved = false,
                            IsDeleted = false
                        },
                        new
                        {
                            ID = new Guid("34b395e8-4e60-4e13-9ea9-043c0f10852d"),
                            CreatedDate = new DateTime(2023, 10, 22, 7, 36, 44, 740, DateTimeKind.Local).AddTicks(7953),
                            IsApproved = false,
                            IsDeleted = false
                        },
                        new
                        {
                            ID = new Guid("4804fa42-5494-4cb0-8c17-f23731b0135d"),
                            CreatedDate = new DateTime(2023, 10, 23, 6, 8, 39, 696, DateTimeKind.Local).AddTicks(988),
                            IsApproved = false,
                            IsDeleted = false
                        },
                        new
                        {
                            ID = new Guid("ef773918-5fff-4c25-84cd-f58b43442e21"),
                            CreatedDate = new DateTime(2024, 2, 13, 0, 58, 57, 854, DateTimeKind.Local).AddTicks(9647),
                            IsApproved = false,
                            IsDeleted = false
                        },
                        new
                        {
                            ID = new Guid("a5d13a52-2dc3-4167-8b8c-4c446844898b"),
                            CreatedDate = new DateTime(2024, 3, 28, 11, 1, 22, 437, DateTimeKind.Local).AddTicks(8788),
                            IsApproved = false,
                            IsDeleted = false
                        },
                        new
                        {
                            ID = new Guid("9072edf5-43e9-45d6-a04e-60e552ac8b57"),
                            CreatedDate = new DateTime(2024, 3, 13, 8, 22, 54, 884, DateTimeKind.Local).AddTicks(4121),
                            IsApproved = false,
                            IsDeleted = false
                        },
                        new
                        {
                            ID = new Guid("09118505-491b-46cd-b154-2f523567c531"),
                            CreatedDate = new DateTime(2024, 1, 31, 22, 38, 6, 696, DateTimeKind.Local).AddTicks(3718),
                            IsApproved = false,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("BtkApiProject.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = new Guid("dd868916-dcde-465f-a89c-313a24d230c6"),
                            CategoryID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2023, 5, 23, 5, 16, 19, 351, DateTimeKind.Local).AddTicks(9581),
                            Description = "Koyun ipsum nisi nemo kalemi gazete nostrum aut.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Fantastic Granite Pants",
                            Price = 7.0
                        },
                        new
                        {
                            ID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CategoryID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2023, 11, 26, 19, 55, 50, 439, DateTimeKind.Local).AddTicks(9076),
                            Description = "Gülüyorum et ötekinden et.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Handcrafted Metal Shoes",
                            Price = 340.0
                        },
                        new
                        {
                            ID = new Guid("18130346-e1b7-41d9-ba97-8e414d50457e"),
                            CategoryID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2024, 2, 23, 19, 6, 57, 939, DateTimeKind.Local).AddTicks(8737),
                            Description = "Eos deleniti mıknatıslı qui gitti dolorem türemiş.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Handmade Metal Pants",
                            Price = 134.0
                        },
                        new
                        {
                            ID = new Guid("95b499c4-34a7-48a2-ac44-bc096de3fc66"),
                            CategoryID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2023, 12, 25, 18, 7, 42, 725, DateTimeKind.Local).AddTicks(5092),
                            Description = "Odio salladı için gidecekmiş gitti.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Generic Frozen Fish",
                            Price = 333.0
                        },
                        new
                        {
                            ID = new Guid("18e74e76-934f-4c06-b3ce-643c87c6dcfd"),
                            CategoryID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2023, 8, 31, 23, 22, 1, 280, DateTimeKind.Local).AddTicks(9890),
                            Description = "Voluptas qui iure amet aut totam doğru.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Tasty Concrete Bike",
                            Price = 381.0
                        },
                        new
                        {
                            ID = new Guid("b9066e07-91f7-44bb-a30b-7122aa190ecc"),
                            CategoryID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2023, 12, 11, 20, 44, 12, 584, DateTimeKind.Local).AddTicks(6318),
                            Description = "Voluptatem explicabo nemo lakin gül yazın masaya ut.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Small Steel Car",
                            Price = 20.0
                        },
                        new
                        {
                            ID = new Guid("eba86dbf-a17a-45e5-bcbf-6aa599af3be1"),
                            CategoryID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2023, 10, 1, 11, 6, 41, 25, DateTimeKind.Local).AddTicks(5057),
                            Description = "Explicabo velit sit incidunt alias göze architecto yapacakmış.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Handcrafted Concrete Ball",
                            Price = 487.0
                        },
                        new
                        {
                            ID = new Guid("80c7de02-40f8-4c82-bd90-212560c06949"),
                            CategoryID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2024, 1, 24, 21, 56, 33, 830, DateTimeKind.Local).AddTicks(2584),
                            Description = "Neque duyulmamış için düşünüyor sıradanlıktan ekşili corporis enim.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Gorgeous Soft Bike",
                            Price = 466.0
                        },
                        new
                        {
                            ID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CategoryID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2024, 4, 3, 15, 34, 33, 72, DateTimeKind.Local).AddTicks(5608),
                            Description = "Doğru filmini enim fugit.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Refined Rubber Cheese",
                            Price = 172.0
                        },
                        new
                        {
                            ID = new Guid("34b395e8-4e60-4e13-9ea9-043c0f10852d"),
                            CategoryID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2024, 4, 11, 4, 17, 19, 873, DateTimeKind.Local).AddTicks(8438),
                            Description = "Gazete sıfat makinesi mıknatıslı.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Sleek Wooden Shirt",
                            Price = 247.0
                        },
                        new
                        {
                            ID = new Guid("4804fa42-5494-4cb0-8c17-f23731b0135d"),
                            CategoryID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2023, 10, 2, 13, 31, 44, 694, DateTimeKind.Local).AddTicks(6595),
                            Description = "Labore gül ötekinden sinema ışık quam aspernatur doloremque.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Small Concrete Tuna",
                            Price = 273.0
                        },
                        new
                        {
                            ID = new Guid("ef773918-5fff-4c25-84cd-f58b43442e21"),
                            CategoryID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2024, 3, 15, 0, 4, 0, 186, DateTimeKind.Local).AddTicks(2388),
                            Description = "Yaptı commodi sunt.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Intelligent Steel Chicken",
                            Price = 53.0
                        },
                        new
                        {
                            ID = new Guid("a5d13a52-2dc3-4167-8b8c-4c446844898b"),
                            CategoryID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2023, 5, 11, 21, 49, 0, 877, DateTimeKind.Local).AddTicks(38),
                            Description = "Çorba incidunt voluptatem sit kalemi duyulmamış esse cesurca voluptate.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Unbranded Wooden Bacon",
                            Price = 145.0
                        },
                        new
                        {
                            ID = new Guid("9072edf5-43e9-45d6-a04e-60e552ac8b57"),
                            CategoryID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2023, 8, 25, 12, 21, 35, 442, DateTimeKind.Local).AddTicks(8785),
                            Description = "Değirmeni eaque gül.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Intelligent Granite Table",
                            Price = 147.0
                        },
                        new
                        {
                            ID = new Guid("09118505-491b-46cd-b154-2f523567c531"),
                            CategoryID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2023, 7, 27, 14, 28, 49, 502, DateTimeKind.Local).AddTicks(5431),
                            Description = "Minima corporis tv gazete et yazın rem non praesentium dağılımı.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Handmade Soft Fish",
                            Price = 451.0
                        },
                        new
                        {
                            ID = new Guid("5e5589fe-77d8-49d2-9bbb-d1a42cba0bf1"),
                            CategoryID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2023, 10, 3, 9, 44, 59, 518, DateTimeKind.Local).AddTicks(3781),
                            Description = "Commodi lambadaki ea magni.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Sleek Frozen Car",
                            Price = 275.0
                        },
                        new
                        {
                            ID = new Guid("fefc43b4-97a8-4713-8071-51930f12cb76"),
                            CategoryID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2024, 1, 4, 17, 14, 15, 14, DateTimeKind.Local).AddTicks(9050),
                            Description = "Aperiam sed beğendim telefonu inventore illo koyun.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Incredible Wooden Fish",
                            Price = 382.0
                        },
                        new
                        {
                            ID = new Guid("9a5c8eee-dfa0-4aee-8e39-c7f34bf24367"),
                            CategoryID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2023, 7, 25, 21, 51, 50, 734, DateTimeKind.Local).AddTicks(3467),
                            Description = "Veniam ducimus sit architecto koştum aut sandalye dicta dolorem.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Rustic Metal Bike",
                            Price = 170.0
                        },
                        new
                        {
                            ID = new Guid("61d00226-a54f-43e4-b94f-ebd81c7acfb0"),
                            CategoryID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2023, 9, 7, 4, 21, 16, 582, DateTimeKind.Local).AddTicks(978),
                            Description = "Quia corporis labore patlıcan ex dolore aliquid voluptatum türemiş consequatur.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Handcrafted Frozen Bacon",
                            Price = 185.0
                        },
                        new
                        {
                            ID = new Guid("3e20bea6-3150-4551-8698-c93bcc384a09"),
                            CategoryID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2023, 6, 13, 17, 58, 0, 737, DateTimeKind.Local).AddTicks(9935),
                            Description = "Olduğu ve ea inventore et minima çobanın çobanın.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Incredible Rubber Bike",
                            Price = 130.0
                        },
                        new
                        {
                            ID = new Guid("32a39a39-0d03-4569-8908-8f0fbd483c65"),
                            CategoryID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2024, 3, 7, 9, 3, 10, 764, DateTimeKind.Local).AddTicks(6078),
                            Description = "Karşıdakine makinesi göze orta modi incidunt türemiş suscipit magni masaya.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Handmade Soft Pants",
                            Price = 347.0
                        },
                        new
                        {
                            ID = new Guid("54b58cfa-5b5e-4b2a-88cd-67e340ac758d"),
                            CategoryID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2023, 9, 10, 7, 56, 29, 84, DateTimeKind.Local).AddTicks(9941),
                            Description = "Magnam sıla quia sunt quam anlamsız laboriosam çorba.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Ergonomic Concrete Pants",
                            Price = 432.0
                        },
                        new
                        {
                            ID = new Guid("eac29877-cf98-49b2-b092-dabde42b829e"),
                            CategoryID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2023, 10, 24, 7, 45, 9, 258, DateTimeKind.Local).AddTicks(6704),
                            Description = "Blanditiis voluptatem et molestiae sayfası aut.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Incredible Plastic Mouse",
                            Price = 127.0
                        },
                        new
                        {
                            ID = new Guid("0d210c85-5f4c-43a6-bcc2-a9546e99601b"),
                            CategoryID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2024, 4, 9, 16, 19, 26, 961, DateTimeKind.Local).AddTicks(3722),
                            Description = "Sinema aut laboriosam koşuyorlar non.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Sleek Metal Sausages",
                            Price = 95.0
                        },
                        new
                        {
                            ID = new Guid("2993cc3b-48d8-4c3a-8662-9ae328688c9c"),
                            CategoryID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2023, 5, 11, 20, 10, 5, 842, DateTimeKind.Local).AddTicks(2074),
                            Description = "Sokaklarda teldeki kulu dışarı ut öyle doloremque çakıl.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Generic Rubber Bike",
                            Price = 328.0
                        },
                        new
                        {
                            ID = new Guid("8df428ba-1d69-45b8-8d40-40e235c957aa"),
                            CategoryID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2023, 8, 31, 7, 49, 47, 323, DateTimeKind.Local).AddTicks(6910),
                            Description = "Lambadaki sinema ipsum karşıdakine.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Handcrafted Cotton Ball",
                            Price = 219.0
                        },
                        new
                        {
                            ID = new Guid("3500e840-e254-4823-90fc-7a8789df67f6"),
                            CategoryID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2023, 9, 6, 12, 47, 5, 790, DateTimeKind.Local).AddTicks(7916),
                            Description = "Et orta için çorba ullam enim ea eius kulu.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Ergonomic Soft Towels",
                            Price = 326.0
                        },
                        new
                        {
                            ID = new Guid("866ea2a9-8721-4251-8022-ad988bd22b8c"),
                            CategoryID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2024, 1, 27, 11, 25, 21, 651, DateTimeKind.Local).AddTicks(4650),
                            Description = "Öyle karşıdakine sevindi umut ekşili voluptate voluptate labore.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Refined Soft Tuna",
                            Price = 440.0
                        },
                        new
                        {
                            ID = new Guid("d11c7b91-2e92-4109-9d55-29adc4506f4f"),
                            CategoryID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2024, 3, 2, 12, 24, 9, 273, DateTimeKind.Local).AddTicks(4713),
                            Description = "Adipisci sequi lakin consectetur.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Ergonomic Fresh Chair",
                            Price = 311.0
                        },
                        new
                        {
                            ID = new Guid("dfbcdf14-bd61-4f63-847a-969b0c517f12"),
                            CategoryID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2023, 12, 2, 18, 2, 3, 249, DateTimeKind.Local).AddTicks(3858),
                            Description = "Velit reprehenderit okuma iusto öyle teldeki karşıdakine ducimus bilgiyasayarı.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Awesome Fresh Chair",
                            Price = 105.0
                        },
                        new
                        {
                            ID = new Guid("1cbbd6f1-b054-44ed-805f-920a998aff90"),
                            CategoryID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2023, 11, 5, 23, 2, 30, 542, DateTimeKind.Local).AddTicks(2371),
                            Description = "Yaptı neque sit dicta in illo yaptı architecto dicta.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Handmade Concrete Computer",
                            Price = 182.0
                        },
                        new
                        {
                            ID = new Guid("065bdc51-a618-45a1-90d7-567ef3843841"),
                            CategoryID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2024, 1, 13, 5, 29, 19, 859, DateTimeKind.Local).AddTicks(2650),
                            Description = "Adresini ut beğendim domates minima bilgiyasayarı explicabo aut.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Gorgeous Concrete Bike",
                            Price = 106.0
                        },
                        new
                        {
                            ID = new Guid("cd2460aa-cf15-4e44-954a-7f7c4c4e5a4e"),
                            CategoryID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2024, 3, 29, 6, 4, 31, 59, DateTimeKind.Local).AddTicks(256),
                            Description = "Aut reprehenderit dolore çakıl.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Refined Cotton Car",
                            Price = 121.0
                        },
                        new
                        {
                            ID = new Guid("57fb9bbb-aa3e-4791-94b7-80ea4883613b"),
                            CategoryID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2024, 1, 9, 5, 30, 59, 910, DateTimeKind.Local).AddTicks(3274),
                            Description = "Consequatur esse quam iusto yazın salladı.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Sleek Fresh Car",
                            Price = 224.0
                        },
                        new
                        {
                            ID = new Guid("388e1e08-a7bd-4552-97c8-b7c0f7b80f11"),
                            CategoryID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2023, 6, 30, 14, 37, 49, 300, DateTimeKind.Local).AddTicks(4760),
                            Description = "Domates et voluptatem şafak consequatur.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Gorgeous Cotton Sausages",
                            Price = 219.0
                        },
                        new
                        {
                            ID = new Guid("7cd76b2b-197a-4ba2-98e1-430b8fd23038"),
                            CategoryID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2023, 10, 11, 18, 45, 25, 806, DateTimeKind.Local).AddTicks(8243),
                            Description = "Değerli teldeki ducimus sed dolor ki kutusu.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Unbranded Steel Keyboard",
                            Price = 373.0
                        },
                        new
                        {
                            ID = new Guid("d369c607-b40a-4375-a39b-53287b41aabb"),
                            CategoryID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2023, 12, 21, 19, 8, 38, 840, DateTimeKind.Local).AddTicks(2936),
                            Description = "Aut anlamsız koştum modi.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Gorgeous Cotton Bacon",
                            Price = 391.0
                        },
                        new
                        {
                            ID = new Guid("61f5f234-13df-4b8e-8558-cccd9b84aab0"),
                            CategoryID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2023, 9, 14, 12, 6, 20, 839, DateTimeKind.Local).AddTicks(4555),
                            Description = "Accusantium nostrum biber aut hesap kapının.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Rustic Metal Chips",
                            Price = 35.0
                        },
                        new
                        {
                            ID = new Guid("96b78027-3570-45bd-8d74-cdaa23c181b8"),
                            CategoryID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2024, 1, 14, 2, 4, 36, 70, DateTimeKind.Local).AddTicks(4708),
                            Description = "Sıfat quis çobanın.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Small Metal Pizza",
                            Price = 409.0
                        },
                        new
                        {
                            ID = new Guid("f2cd9efc-1bdb-48ad-ad51-13bb4daff119"),
                            CategoryID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2023, 6, 14, 2, 31, 8, 22, DateTimeKind.Local).AddTicks(3156),
                            Description = "Quaerat magnam layıkıyla patlıcan qui nesciunt amet şafak.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Sleek Fresh Computer",
                            Price = 180.0
                        },
                        new
                        {
                            ID = new Guid("c66915b3-d9f8-4bb6-bd46-828e5a946a61"),
                            CategoryID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2023, 4, 28, 20, 0, 46, 574, DateTimeKind.Local).AddTicks(2027),
                            Description = "Bundan balıkhaneye ipsam tv.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Handmade Cotton Shoes",
                            Price = 394.0
                        },
                        new
                        {
                            ID = new Guid("6d776c03-bd8a-4ed4-965d-92bd5d196380"),
                            CategoryID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2023, 5, 29, 3, 16, 42, 115, DateTimeKind.Local).AddTicks(8220),
                            Description = "Mıknatıslı quia lambadaki sevindi eius esse sit adanaya.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Fantastic Fresh Computer",
                            Price = 279.0
                        },
                        new
                        {
                            ID = new Guid("99bd8cd0-f4c4-403a-b678-a3c233ed9f7e"),
                            CategoryID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2023, 10, 25, 13, 21, 9, 279, DateTimeKind.Local).AddTicks(4396),
                            Description = "Aspernatur odit için patlıcan aperiam exercitationem aperiam odio.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Handmade Frozen Chicken",
                            Price = 290.0
                        },
                        new
                        {
                            ID = new Guid("5f6ac016-ec06-4c35-8f74-164c3e0724d3"),
                            CategoryID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2023, 7, 31, 3, 51, 18, 232, DateTimeKind.Local).AddTicks(5459),
                            Description = "Mutlu quia et yaptı kalemi.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Intelligent Frozen Shirt",
                            Price = 379.0
                        },
                        new
                        {
                            ID = new Guid("cb35d17f-0bdb-4237-9cd9-27e6f436cdc4"),
                            CategoryID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2024, 3, 23, 11, 30, 38, 296, DateTimeKind.Local).AddTicks(7040),
                            Description = "Nihil architecto in consequatur ut.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Refined Frozen Car",
                            Price = 367.0
                        },
                        new
                        {
                            ID = new Guid("65e02ef9-a536-4c6a-9f18-1c6dd9af4fd6"),
                            CategoryID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2023, 11, 7, 2, 48, 53, 304, DateTimeKind.Local).AddTicks(3568),
                            Description = "Yazın sinema koşuyorlar okuma umut neque ad ratione mi.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Handcrafted Concrete Car",
                            Price = 58.0
                        },
                        new
                        {
                            ID = new Guid("35677582-d7f7-4230-ab73-35d5fdc19a1b"),
                            CategoryID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2023, 6, 28, 5, 49, 47, 994, DateTimeKind.Local).AddTicks(6330),
                            Description = "Ut blanditiis beatae.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Small Steel Pants",
                            Price = 74.0
                        },
                        new
                        {
                            ID = new Guid("de22d097-5f6c-42bc-947d-5ada70509533"),
                            CategoryID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2023, 6, 6, 19, 22, 17, 143, DateTimeKind.Local).AddTicks(9697),
                            Description = "Ki sequi dolore yapacakmış.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Fantastic Soft Cheese",
                            Price = 24.0
                        },
                        new
                        {
                            ID = new Guid("8c4b66b6-8fea-4330-be08-5e548e473a7b"),
                            CategoryID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2023, 5, 2, 22, 53, 45, 550, DateTimeKind.Local).AddTicks(9454),
                            Description = "Dağılımı quia vitae.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Tasty Wooden Pants",
                            Price = 492.0
                        },
                        new
                        {
                            ID = new Guid("7532d41d-4ec0-4c29-9864-25d1e936ccec"),
                            CategoryID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2023, 7, 1, 22, 16, 30, 887, DateTimeKind.Local).AddTicks(9900),
                            Description = "Sit dignissimos sinema tempora autem.",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Small Frozen Bacon",
                            Price = 495.0
                        });
                });

            modelBuilder.Entity("BtkApiProject.Domain.Entities.ProductDetail", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProductID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("ProductID")
                        .IsUnique();

                    b.ToTable("ProductDetails");

                    b.HasData(
                        new
                        {
                            ID = new Guid("dd868916-dcde-465f-a89c-313a24d230c6"),
                            CreatedDate = new DateTime(2023, 10, 17, 0, 30, 0, 424, DateTimeKind.Local).AddTicks(2888),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("dd868916-dcde-465f-a89c-313a24d230c6"),
                            Quantity = 26
                        },
                        new
                        {
                            ID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            CreatedDate = new DateTime(2024, 2, 26, 7, 34, 8, 103, DateTimeKind.Local).AddTicks(3068),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("8ed24296-d7a3-438b-be89-358a6186a06b"),
                            Quantity = 29
                        },
                        new
                        {
                            ID = new Guid("18130346-e1b7-41d9-ba97-8e414d50457e"),
                            CreatedDate = new DateTime(2024, 3, 17, 14, 37, 33, 561, DateTimeKind.Local).AddTicks(3692),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("18130346-e1b7-41d9-ba97-8e414d50457e"),
                            Quantity = 18
                        },
                        new
                        {
                            ID = new Guid("95b499c4-34a7-48a2-ac44-bc096de3fc66"),
                            CreatedDate = new DateTime(2024, 3, 16, 4, 50, 16, 728, DateTimeKind.Local).AddTicks(1935),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("95b499c4-34a7-48a2-ac44-bc096de3fc66"),
                            Quantity = 48
                        },
                        new
                        {
                            ID = new Guid("18e74e76-934f-4c06-b3ce-643c87c6dcfd"),
                            CreatedDate = new DateTime(2023, 4, 30, 12, 26, 36, 675, DateTimeKind.Local).AddTicks(5488),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("18e74e76-934f-4c06-b3ce-643c87c6dcfd"),
                            Quantity = 34
                        },
                        new
                        {
                            ID = new Guid("b9066e07-91f7-44bb-a30b-7122aa190ecc"),
                            CreatedDate = new DateTime(2024, 3, 8, 13, 45, 11, 694, DateTimeKind.Local).AddTicks(6300),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("b9066e07-91f7-44bb-a30b-7122aa190ecc"),
                            Quantity = 13
                        },
                        new
                        {
                            ID = new Guid("eba86dbf-a17a-45e5-bcbf-6aa599af3be1"),
                            CreatedDate = new DateTime(2023, 12, 6, 3, 16, 7, 108, DateTimeKind.Local).AddTicks(5372),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("eba86dbf-a17a-45e5-bcbf-6aa599af3be1"),
                            Quantity = 31
                        },
                        new
                        {
                            ID = new Guid("80c7de02-40f8-4c82-bd90-212560c06949"),
                            CreatedDate = new DateTime(2023, 10, 15, 13, 1, 16, 571, DateTimeKind.Local).AddTicks(8412),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("80c7de02-40f8-4c82-bd90-212560c06949"),
                            Quantity = 47
                        },
                        new
                        {
                            ID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            CreatedDate = new DateTime(2023, 9, 29, 5, 0, 34, 533, DateTimeKind.Local).AddTicks(4957),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("c398bbac-0820-4456-8f24-bd5bcaf3771b"),
                            Quantity = 49
                        },
                        new
                        {
                            ID = new Guid("34b395e8-4e60-4e13-9ea9-043c0f10852d"),
                            CreatedDate = new DateTime(2023, 8, 7, 14, 16, 38, 169, DateTimeKind.Local).AddTicks(6546),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("34b395e8-4e60-4e13-9ea9-043c0f10852d"),
                            Quantity = 49
                        },
                        new
                        {
                            ID = new Guid("4804fa42-5494-4cb0-8c17-f23731b0135d"),
                            CreatedDate = new DateTime(2023, 9, 10, 20, 9, 16, 942, DateTimeKind.Local).AddTicks(3441),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("4804fa42-5494-4cb0-8c17-f23731b0135d"),
                            Quantity = 50
                        },
                        new
                        {
                            ID = new Guid("ef773918-5fff-4c25-84cd-f58b43442e21"),
                            CreatedDate = new DateTime(2023, 9, 4, 23, 22, 13, 891, DateTimeKind.Local).AddTicks(3631),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("ef773918-5fff-4c25-84cd-f58b43442e21"),
                            Quantity = 42
                        },
                        new
                        {
                            ID = new Guid("a5d13a52-2dc3-4167-8b8c-4c446844898b"),
                            CreatedDate = new DateTime(2023, 12, 28, 16, 40, 4, 882, DateTimeKind.Local).AddTicks(3553),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("a5d13a52-2dc3-4167-8b8c-4c446844898b"),
                            Quantity = 2
                        },
                        new
                        {
                            ID = new Guid("9072edf5-43e9-45d6-a04e-60e552ac8b57"),
                            CreatedDate = new DateTime(2023, 8, 6, 10, 51, 8, 157, DateTimeKind.Local).AddTicks(7668),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("9072edf5-43e9-45d6-a04e-60e552ac8b57"),
                            Quantity = 8
                        },
                        new
                        {
                            ID = new Guid("09118505-491b-46cd-b154-2f523567c531"),
                            CreatedDate = new DateTime(2023, 11, 12, 12, 3, 9, 690, DateTimeKind.Local).AddTicks(2751),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("09118505-491b-46cd-b154-2f523567c531"),
                            Quantity = 41
                        },
                        new
                        {
                            ID = new Guid("5e5589fe-77d8-49d2-9bbb-d1a42cba0bf1"),
                            CreatedDate = new DateTime(2023, 8, 16, 4, 49, 55, 481, DateTimeKind.Local).AddTicks(8014),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("5e5589fe-77d8-49d2-9bbb-d1a42cba0bf1"),
                            Quantity = 22
                        },
                        new
                        {
                            ID = new Guid("fefc43b4-97a8-4713-8071-51930f12cb76"),
                            CreatedDate = new DateTime(2023, 5, 15, 7, 47, 36, 25, DateTimeKind.Local).AddTicks(7732),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("fefc43b4-97a8-4713-8071-51930f12cb76"),
                            Quantity = 43
                        },
                        new
                        {
                            ID = new Guid("9a5c8eee-dfa0-4aee-8e39-c7f34bf24367"),
                            CreatedDate = new DateTime(2023, 9, 12, 2, 21, 55, 833, DateTimeKind.Local).AddTicks(2070),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("9a5c8eee-dfa0-4aee-8e39-c7f34bf24367"),
                            Quantity = 31
                        },
                        new
                        {
                            ID = new Guid("61d00226-a54f-43e4-b94f-ebd81c7acfb0"),
                            CreatedDate = new DateTime(2023, 5, 26, 4, 59, 17, 832, DateTimeKind.Local).AddTicks(6720),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("61d00226-a54f-43e4-b94f-ebd81c7acfb0"),
                            Quantity = 23
                        },
                        new
                        {
                            ID = new Guid("3e20bea6-3150-4551-8698-c93bcc384a09"),
                            CreatedDate = new DateTime(2023, 12, 6, 16, 54, 18, 891, DateTimeKind.Local).AddTicks(2721),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("3e20bea6-3150-4551-8698-c93bcc384a09"),
                            Quantity = 35
                        },
                        new
                        {
                            ID = new Guid("32a39a39-0d03-4569-8908-8f0fbd483c65"),
                            CreatedDate = new DateTime(2023, 6, 16, 15, 8, 55, 451, DateTimeKind.Local).AddTicks(9473),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("32a39a39-0d03-4569-8908-8f0fbd483c65"),
                            Quantity = 11
                        },
                        new
                        {
                            ID = new Guid("54b58cfa-5b5e-4b2a-88cd-67e340ac758d"),
                            CreatedDate = new DateTime(2023, 8, 24, 14, 45, 39, 377, DateTimeKind.Local).AddTicks(3414),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("54b58cfa-5b5e-4b2a-88cd-67e340ac758d"),
                            Quantity = 17
                        },
                        new
                        {
                            ID = new Guid("eac29877-cf98-49b2-b092-dabde42b829e"),
                            CreatedDate = new DateTime(2024, 4, 2, 23, 22, 42, 620, DateTimeKind.Local).AddTicks(1040),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("eac29877-cf98-49b2-b092-dabde42b829e"),
                            Quantity = 26
                        },
                        new
                        {
                            ID = new Guid("0d210c85-5f4c-43a6-bcc2-a9546e99601b"),
                            CreatedDate = new DateTime(2023, 11, 19, 3, 21, 44, 744, DateTimeKind.Local).AddTicks(2416),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("0d210c85-5f4c-43a6-bcc2-a9546e99601b"),
                            Quantity = 23
                        },
                        new
                        {
                            ID = new Guid("2993cc3b-48d8-4c3a-8662-9ae328688c9c"),
                            CreatedDate = new DateTime(2024, 2, 20, 6, 11, 49, 105, DateTimeKind.Local).AddTicks(7716),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("2993cc3b-48d8-4c3a-8662-9ae328688c9c"),
                            Quantity = 43
                        },
                        new
                        {
                            ID = new Guid("8df428ba-1d69-45b8-8d40-40e235c957aa"),
                            CreatedDate = new DateTime(2024, 3, 2, 6, 56, 11, 136, DateTimeKind.Local).AddTicks(9838),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("8df428ba-1d69-45b8-8d40-40e235c957aa"),
                            Quantity = 43
                        },
                        new
                        {
                            ID = new Guid("3500e840-e254-4823-90fc-7a8789df67f6"),
                            CreatedDate = new DateTime(2024, 1, 13, 10, 27, 42, 582, DateTimeKind.Local).AddTicks(9489),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("3500e840-e254-4823-90fc-7a8789df67f6"),
                            Quantity = 2
                        },
                        new
                        {
                            ID = new Guid("866ea2a9-8721-4251-8022-ad988bd22b8c"),
                            CreatedDate = new DateTime(2024, 2, 6, 11, 54, 38, 568, DateTimeKind.Local).AddTicks(9959),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("866ea2a9-8721-4251-8022-ad988bd22b8c"),
                            Quantity = 29
                        },
                        new
                        {
                            ID = new Guid("d11c7b91-2e92-4109-9d55-29adc4506f4f"),
                            CreatedDate = new DateTime(2024, 4, 7, 13, 59, 22, 934, DateTimeKind.Local).AddTicks(8720),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("d11c7b91-2e92-4109-9d55-29adc4506f4f"),
                            Quantity = 45
                        },
                        new
                        {
                            ID = new Guid("dfbcdf14-bd61-4f63-847a-969b0c517f12"),
                            CreatedDate = new DateTime(2024, 3, 23, 12, 53, 38, 243, DateTimeKind.Local).AddTicks(2028),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("dfbcdf14-bd61-4f63-847a-969b0c517f12"),
                            Quantity = 47
                        },
                        new
                        {
                            ID = new Guid("1cbbd6f1-b054-44ed-805f-920a998aff90"),
                            CreatedDate = new DateTime(2023, 5, 22, 8, 47, 59, 383, DateTimeKind.Local).AddTicks(1948),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("1cbbd6f1-b054-44ed-805f-920a998aff90"),
                            Quantity = 12
                        },
                        new
                        {
                            ID = new Guid("065bdc51-a618-45a1-90d7-567ef3843841"),
                            CreatedDate = new DateTime(2023, 5, 18, 22, 53, 54, 827, DateTimeKind.Local).AddTicks(1037),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("065bdc51-a618-45a1-90d7-567ef3843841"),
                            Quantity = 17
                        },
                        new
                        {
                            ID = new Guid("cd2460aa-cf15-4e44-954a-7f7c4c4e5a4e"),
                            CreatedDate = new DateTime(2023, 7, 22, 21, 42, 12, 296, DateTimeKind.Local).AddTicks(8105),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("cd2460aa-cf15-4e44-954a-7f7c4c4e5a4e"),
                            Quantity = 1
                        },
                        new
                        {
                            ID = new Guid("57fb9bbb-aa3e-4791-94b7-80ea4883613b"),
                            CreatedDate = new DateTime(2023, 12, 21, 18, 17, 49, 636, DateTimeKind.Local).AddTicks(8288),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("57fb9bbb-aa3e-4791-94b7-80ea4883613b"),
                            Quantity = 3
                        },
                        new
                        {
                            ID = new Guid("388e1e08-a7bd-4552-97c8-b7c0f7b80f11"),
                            CreatedDate = new DateTime(2024, 3, 19, 13, 26, 14, 740, DateTimeKind.Local).AddTicks(3660),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("388e1e08-a7bd-4552-97c8-b7c0f7b80f11"),
                            Quantity = 13
                        },
                        new
                        {
                            ID = new Guid("7cd76b2b-197a-4ba2-98e1-430b8fd23038"),
                            CreatedDate = new DateTime(2024, 3, 7, 20, 19, 33, 968, DateTimeKind.Local).AddTicks(114),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("7cd76b2b-197a-4ba2-98e1-430b8fd23038"),
                            Quantity = 6
                        },
                        new
                        {
                            ID = new Guid("d369c607-b40a-4375-a39b-53287b41aabb"),
                            CreatedDate = new DateTime(2024, 2, 9, 4, 33, 19, 428, DateTimeKind.Local).AddTicks(4072),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("d369c607-b40a-4375-a39b-53287b41aabb"),
                            Quantity = 28
                        },
                        new
                        {
                            ID = new Guid("61f5f234-13df-4b8e-8558-cccd9b84aab0"),
                            CreatedDate = new DateTime(2023, 9, 28, 19, 34, 10, 848, DateTimeKind.Local).AddTicks(6339),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("61f5f234-13df-4b8e-8558-cccd9b84aab0"),
                            Quantity = 7
                        },
                        new
                        {
                            ID = new Guid("96b78027-3570-45bd-8d74-cdaa23c181b8"),
                            CreatedDate = new DateTime(2023, 12, 2, 17, 46, 51, 192, DateTimeKind.Local).AddTicks(9759),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("96b78027-3570-45bd-8d74-cdaa23c181b8"),
                            Quantity = 26
                        },
                        new
                        {
                            ID = new Guid("f2cd9efc-1bdb-48ad-ad51-13bb4daff119"),
                            CreatedDate = new DateTime(2023, 6, 23, 3, 4, 31, 328, DateTimeKind.Local).AddTicks(8318),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("f2cd9efc-1bdb-48ad-ad51-13bb4daff119"),
                            Quantity = 35
                        },
                        new
                        {
                            ID = new Guid("c66915b3-d9f8-4bb6-bd46-828e5a946a61"),
                            CreatedDate = new DateTime(2023, 9, 9, 16, 40, 12, 507, DateTimeKind.Local).AddTicks(1503),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("c66915b3-d9f8-4bb6-bd46-828e5a946a61"),
                            Quantity = 26
                        },
                        new
                        {
                            ID = new Guid("6d776c03-bd8a-4ed4-965d-92bd5d196380"),
                            CreatedDate = new DateTime(2024, 2, 2, 2, 42, 49, 499, DateTimeKind.Local).AddTicks(4043),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("6d776c03-bd8a-4ed4-965d-92bd5d196380"),
                            Quantity = 49
                        },
                        new
                        {
                            ID = new Guid("99bd8cd0-f4c4-403a-b678-a3c233ed9f7e"),
                            CreatedDate = new DateTime(2023, 11, 12, 5, 54, 48, 200, DateTimeKind.Local).AddTicks(1284),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("99bd8cd0-f4c4-403a-b678-a3c233ed9f7e"),
                            Quantity = 40
                        },
                        new
                        {
                            ID = new Guid("5f6ac016-ec06-4c35-8f74-164c3e0724d3"),
                            CreatedDate = new DateTime(2023, 9, 10, 19, 43, 47, 969, DateTimeKind.Local).AddTicks(740),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("5f6ac016-ec06-4c35-8f74-164c3e0724d3"),
                            Quantity = 1
                        },
                        new
                        {
                            ID = new Guid("cb35d17f-0bdb-4237-9cd9-27e6f436cdc4"),
                            CreatedDate = new DateTime(2023, 9, 24, 3, 47, 44, 920, DateTimeKind.Local).AddTicks(3125),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("cb35d17f-0bdb-4237-9cd9-27e6f436cdc4"),
                            Quantity = 5
                        },
                        new
                        {
                            ID = new Guid("65e02ef9-a536-4c6a-9f18-1c6dd9af4fd6"),
                            CreatedDate = new DateTime(2023, 5, 5, 15, 50, 27, 583, DateTimeKind.Local).AddTicks(5125),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("65e02ef9-a536-4c6a-9f18-1c6dd9af4fd6"),
                            Quantity = 6
                        },
                        new
                        {
                            ID = new Guid("35677582-d7f7-4230-ab73-35d5fdc19a1b"),
                            CreatedDate = new DateTime(2023, 9, 26, 23, 15, 44, 377, DateTimeKind.Local).AddTicks(7717),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("35677582-d7f7-4230-ab73-35d5fdc19a1b"),
                            Quantity = 15
                        },
                        new
                        {
                            ID = new Guid("de22d097-5f6c-42bc-947d-5ada70509533"),
                            CreatedDate = new DateTime(2023, 10, 18, 15, 24, 28, 341, DateTimeKind.Local).AddTicks(4331),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("de22d097-5f6c-42bc-947d-5ada70509533"),
                            Quantity = 8
                        },
                        new
                        {
                            ID = new Guid("8c4b66b6-8fea-4330-be08-5e548e473a7b"),
                            CreatedDate = new DateTime(2023, 9, 18, 22, 37, 49, 440, DateTimeKind.Local).AddTicks(4914),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("8c4b66b6-8fea-4330-be08-5e548e473a7b"),
                            Quantity = 30
                        },
                        new
                        {
                            ID = new Guid("7532d41d-4ec0-4c29-9864-25d1e936ccec"),
                            CreatedDate = new DateTime(2024, 3, 19, 5, 47, 21, 334, DateTimeKind.Local).AddTicks(5236),
                            IsApproved = false,
                            IsDeleted = false,
                            ProductID = new Guid("7532d41d-4ec0-4c29-9864-25d1e936ccec"),
                            Quantity = 9
                        });
                });

            modelBuilder.Entity("BtkApiProject.Domain.Entities.Joins.OrderProduct", b =>
                {
                    b.HasOne("BtkApiProject.Domain.Entities.Order", "Order")
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BtkApiProject.Domain.Entities.Product", "Product")
                        .WithMany("OrderProducts")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BtkApiProject.Domain.Entities.Product", b =>
                {
                    b.HasOne("BtkApiProject.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BtkApiProject.Domain.Entities.ProductDetail", b =>
                {
                    b.HasOne("BtkApiProject.Domain.Entities.Product", "Product")
                        .WithOne("ProductDetail")
                        .HasForeignKey("BtkApiProject.Domain.Entities.ProductDetail", "ProductID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BtkApiProject.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BtkApiProject.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("BtkApiProject.Domain.Entities.Product", b =>
                {
                    b.Navigation("OrderProducts");

                    b.Navigation("ProductDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
